### PR TITLE
[ci] Enable Clang Static Analyzer

### PR DESCRIPTION
**Pull request by yetist**
clang analyzer

### CODE REVIEW

**Comment by yetist** [comment]
need enable gh-pages.

**Comment by raveit65** [comment]
Done.
I have draft some 1.22 .0 releases, eg. https://github.com/mate-desktop/mate-settings-daemon/releases
Should i change links in `before_scripts`before_scripts` ?
Might be better to use tarballs form gitub source.

**Comment by yetist** [comment]
I don't object, maybe it can ease the pressure on the server.

**Comment by yetist** [comment]
@raveit65 

I created a new PR to test release tarballs on github, maybe you are interested #427

**Comment by raveit65** [comment]
Results are there now.
https://mate-control-center.mate-desktop.dev/

**Comment by yetist** [comment]
> Results are there now.
> https://mate-control-center.mate-desktop.dev/

Thank you.

**Pull request merged**
