### PR TITLE
Fix dangling pointer errors

### PR DESCRIPTION
**Pull request by pudh4418**

### CODE REVIEW

**Comment by raveit65** [comment]
Where do you see a dangling pointer?

**Comment by pudh4418** [comment]
When the second time you double clicking the light bulb, it outputs some error messages like:
```
(mate-mouse-properties:2740): GLib-CRITICAL **: Source ID 190 was not found when attempting to remove it
```
It is because after removing the source, the source id variable still contains old value. So next time it will try to remove an already removed source. This is a dangling pointer error.
So just simply reset these variables to zero after removing the source.

**Comment by raveit65** [comment]
yeah, confirmed

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-control-center/commit/fa57391891309545aebc94fae4d79f6fae683659
Thank you

**Pull request closed without merging**
