### PR TITLE
Touchpad settings: Support edge and two-finger scrolling independently

### PR DESCRIPTION
**Pull request by clefebvre**

### CODE REVIEW

**Comment by monsta** [comment]
@flexiondotorg: can you please test it on your laptop so we could merge it for 1.14?
You'll need to apply https://github.com/mate-desktop/mate-settings-daemon/pull/137 first.

**Comment by flexiondotorg** [comment]
I don't have a multi touch capable trackpad laptop anymore 😢

**Comment by monsta** [comment]
Hmm... I guess we'll have to merge it then and wait for feedback after 1.14 release...

**Comment by monsta** [comment]
@lukefromdc: maybe you can test this + https://github.com/mate-desktop/mate-settings-daemon/pull/137?
I think it should work the same with GTK+3.

**Comment by lukefromdc** [comment]
I don't know how to do two-fingered scrolling on any laptop, it's one
of those
things I've never used. I will do a test build tomorrow or tonight
anyway, will
be on the road today.

On 3/18/2016 at 9:58 AM, "monsta"  wrote:

	@lukefromdc: maybe you can test this +
mate-desktop/mate-settings-daemon#137?
 I think it should work the same with GTK+3.

**Comment by lukefromdc** [comment]
A quick GTK3 test build before I hit the road built OK but crashed on
startup,
then relaunched and crashed over and over again on a desktop machine
(no touchpad present).

On 3/18/2016 at 9:58 AM, "monsta"  wrote:

	@lukefromdc: maybe you can test this +
mate-desktop/mate-settings-daemon#137?
 I think it should work the same with GTK+3.

**Comment by monsta** [comment]
Just in case - did you build https://github.com/mate-desktop/mate-settings-daemon/pull/137 before it? It's needed for this PR to work.

**Comment by lukefromdc** [comment]
Never knew that, and I am about to head out, no more time right now. I
just pulled your whole touchpad-improvements
branch  as a tarball from the website, built it and tried to run it. 
Wouldn't that patch be in the tarball though?

On 3/18/2016 at 12:44 PM, "monsta"  wrote:

	Just in case - did you build mate-desktop/mate-settings-daemon#137
before it? It's needed for this PR to work.

**Comment by monsta** [comment]
Oh... no, I only mentioned it in the comments above. It's not my branch actually, I'm just trying to give it some testing before merging. Unfortunately, I don't have any laptops around to test it myself...

**Comment by monsta** [comment]
@lukefromdc: any luck with testing https://github.com/mate-desktop/mate-settings-daemon/pull/137 + this one?

**Comment by lukefromdc** [comment]
My one test was of the entire branch pulled as a tarball, presumably with
all three commits. The result was an unusable session of mate-settings-daemon
constantly crashing and restarting.

**Comment by monsta** [comment]
Well, you'll need the corresponding branch from m-s-d too. Using only one of these two PRs will result in crashes.

**Comment by lukefromdc** [comment]
I won't be able to do that today as I am busy with other things. Also do 
remember-this is a desktop, and on the laptop I do have I don't know
how to use two-fingered anything. Right now I am focussed on setting
up a GTK2 partition (which I won't be able to keep for space reasons)
to test out the mate-panel work in GTK2.

**Comment by lukefromdc** [comment]
OK, I've now got tarballs of both the MCC and MSD branches, will build
and test them together tonight, recover using a Cinnamon seesion if
they break(fsck happens in this kind of work so I prepare for it).

**Comment by lukefromdc** [comment]
Just built both branches together with GTK 3.20. Built fine, but still
got mate-settings-daemon crashing over and over again.

**Comment by monsta** [comment]
@raveit65: maybe you could give it a try? Just to check if there will be any crashes...

**Comment by monsta** [comment]
@raveit65 @lukefromdc forgot to tell: it's actually possible to test UI and changes in GSettings even on the desktop, without any touchpad. Just apply this simple patch:

```diff
diff --git a/capplets/mouse/mate-mouse-properties.c b/capplets/mouse/mate-mouse-properties.c
index 0a6fb88..b545f9c 100644
--- a/capplets/mouse/mate-mouse-properties.c
+++ b/capplets/mouse/mate-mouse-properties.c
@@ -369,7 +369,7 @@ setup_dialog (GtkBuilder *dialog)
                G_SETTINGS_BIND_DEFAULT);
 
        /* Trackpad page */
-       if (find_synaptics () == FALSE)
+       if (/*find_synaptics () == */FALSE)
                gtk_notebook_remove_page (GTK_NOTEBOOK (WID ("prefs_widget")), -1);
        else {
                g_settings_bind (touchpad_settings, "touchpad-enabled",
```
Now the "Touchpad" tab in ```mate-mouse-properties``` will always be visible, even when touchpad isn't found in the system. :smile:

**Comment by monsta** [comment]
Bumped required m-s-d version to 1.13.1, as per https://github.com/mate-desktop/mate-settings-daemon/pull/137#issuecomment-200748646.

**Comment by monsta** [comment]
@lukefromdc: just tested this + https://github.com/mate-desktop/mate-settings-daemon/pull/137 with GTK+3 (3.18.9). Used the mentioned patch to test UI on the desktop. Well, all works fine, no crashes...

**Comment by lukefromdc** [comment]
The crash I got was in mate-settings-daemon itself, wonder if this is GTK 3.20 specific?

**Comment by monsta** [comment]
@raveit65: did you see any m-s-d crashes with 3.19/3.20?

**Comment by raveit65** [comment]
Well, with latest releases m-s-d (mate-settings-daemon-1.13.1-11.fc24.x86_64) i didn't notify any crashes or abrt alarms in fedora 24 on my main box.
I will test now all this stuff here on my notebook, but........
@monsta 
Does updating m-c-c and m-s-d work with 1.12 environment?
I use fedora-22 or rhel-7.2 there, and i do not have any free diskspace to set up a third installation with f24 which use 1.13.x.

**Comment by monsta** [comment]
I don't know, didn't test it with 1.12.

**Comment by raveit65** [comment]
Ok, i can test, fedora 22 use gtk3 version from 1.13 branch, my fault....
......to much different installations here.

**Comment by raveit65** [comment]
Ok, m-s-d and m-c-c are updated on my notebook (f22)
All settings in touchpad tab are working in a quick test.
And i do not get crashes or abrt alarms with m-s-d.
If those are gtk+-3.20 related, i'm sorry to say i can't test this in the moment.
I won't update my notebook before f24 is released.

Honestly, i don't understand what natural scrolling is, btw. is see no different.

**Comment by monsta** [comment]
Natural scrolling is a reverse scrolling. It's like when you hold left mouse button in atril and drag it to scroll the document. Or same with large pictures in eom. You move mouse down, the document or the picture scrolls up. This is the opposite to scrollbar behaviour, so it's reverse.

I have no idea who first called it "natural", but that person most probably was a smartphone/tablet user. This type of scrolling is performed there using your fingers.

**Comment by raveit65** [comment]
@monsta 
@clefebvre 
Fedora 24 alpha freeze is over.
So if you merge this PR + m-s-d  PR and release new 1.13.x tarballs, i can build theme for fedora 24 and the gtk3 repo, and we have a minimal chance that more people can test this new settings, before we release 1.14.

**Comment by monsta** [comment]
I'd gladly merge it - but Luke has m-s-d crashing right on startup :confused:

**Comment by raveit65** [comment]
Well, up to you, i only wanted to give you an option for more testing :smile: 
.....we can use it also for 1.6.

**Comment by XRevan86** [comment]
Looks fine to me. mate-settings-daemon (Gtk2) didn't crash, all settings that worked before work now.
Horizontal scrolling didn't and doesn't work, so are mouse click emulations (MATE settings are simply ignored, two-finger always emulates right click). Probably hardware related.

**Comment by lukefromdc** [comment]
I have not been able to fix this when using tarballs of the msd and mcc
branches in question. Can anyone else test this in GTK 3.20? I will
run another test of this today and see if I can get any information from
the crashes themselves.

**Comment by lukefromdc** [comment]
I just found the source of the crashes-a stupid build time error on this
end. Go ahead and merge it, the code was never the issue.

I normally build with --disable-schemas-compile so the file build
by recompiling schemas doesn't get copied into my debian packages
by checkinstall. For testing though I was just using make-install, and
this change includes schema changes. Had I been building .debs they 
would have been recompiled when the .debs were installed, but not
on a make install with this build option, thus the crash on wrong schemas.

**Comment by monsta** [comment]
Well, good it's solved at last :smile:

**Pull request merged**
