### PR TITLE
help: update default apps

### PR DESCRIPTION
**Pull request by rbuj**
Test:
```
$ yelp file:///usr/share/help/C/mate-control-center/config-default-apps.xml 
```

### CODE REVIEW

**Comment by lukefromdc** [comment]
I get a completely different page, 
Desktop User Guide » Configuring Your Desktop » Personal »
on opening help from m-c-c ->perferred applications so I don't know how to bring up this help page with severely obsolete program names. That said, wherever this comes up, it urgently needs this update

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@lukefromdc 
Does it work for you?
And  can we merge this?

**Comment by lukefromdc** [comment]
I never got that help file to come up, but go ahead and merge it. I was probably looking in the wrong place and am now out of town

On 3/11/2021 at 6:52 AM, "raveit65" ***@***.***> wrote:
>
***@***.***

**Pull request merged**
