### PR TITLE
time-admin: theming

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Is there a chance to to call original author of this application to inform him about changes?

**Comment by rbuj** [comment]
@raveit65 @zhuyaliang @mate-desktop/core-team There is a lot of things to do with time-admin:
- App/Window icon: https://github.com/mate-desktop/mate-control-center/pull/467
- Buttons: https://github.com/mate-desktop/mate-control-center/pull/468
- Theming: https://github.com/mate-desktop/mate-control-center/pull/471
- Write UI files and follow [GNOME 2 Human Interface Guidelines](https://developer.gnome.org/hig-book/): Assigned [time-admin.ui](https://github.com/mate-desktop/mate-control-center/tree/test-time-admin-ui). Not Assigned: Time Zone, Message Dialogs with images.
- Fix code formatting: Not Assigned
- Remove global variables: WindowLogin, TimeoutFlag: Not Assigned
- Use private types (i.e. class): Not Assigned
- a11y: Not Assigned
- ...

**Comment by zhuyaliang** [comment]
Do ```ui``` files have to be used in interface design?

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Should i add @zhuyaliang  to mate-control-center and give him commit rights?

**Comment by yetist** [comment]
@rbuj 

I agree with you that the time-admin still needs to do a lot of work.
It would be better if the original author could re-optimize the code, or if he wants others to help him improve the code.

**Comment by rbuj** [comment]
> Do `ui` files have to be used in interface design?

Yes.

```shell
$ find . -name *.ui 
./capplets/keybindings/mate-keybinding-properties.ui
./capplets/appearance/data/appearance.ui
./capplets/network/mate-network-properties.ui
./capplets/about-me/mate-about-me-password.ui
./capplets/about-me/mate-about-me-fingerprint.ui
./capplets/about-me/mate-about-me-dialog.ui
./capplets/mouse/mate-mouse-properties.ui
./capplets/default-applications/mate-default-applications-properties.ui
./capplets/display/display-capplet.ui
./capplets/accessibility/at-properties/at-enable-dialog.ui
./capplets/keyboard/mate-keyboard-properties-options-dialog.ui
./capplets/keyboard/mate-keyboard-properties-dialog.ui
./capplets/keyboard/mate-keyboard-properties-a11y-notifications.ui
./capplets/keyboard/mate-keyboard-properties-layout-chooser.ui
./capplets/keyboard/mate-keyboard-properties-model-chooser.ui
```

**Comment by zhuyaliang** [comment]
In order to maintain unity, I accept this proposal, but I'm not very good at designing UI files, and I can't help you with that.

**Comment by raveit65** [comment]
> There is a lot of things to do with time-admin:
> - App/Window icon: https://github.com/mate-desktop/mate-control-center/pull/467
> - Buttons: https://github.com/mate-desktop/mate-control-center/pull/468
> - Theming: https://github.com/mate-desktop/mate-control-center/pull/471
> - Write UI files and follow [GNOME 2 Human Interface Guidelines](https://developer.gnome.org/hig-book/): Assigned [time-admin.ui](https://github.com/mate-desktop/mate-control-center/tree/test-time-admin-ui). Not Assigned: Time Zone, Message Dialogs with images.
> - Fix code formatting: Not Assigned
> - Remove global variables: WindowLogin, TimeoutFlag: Not Assigned
> - Use private types (i.e. class): Not Assigned
> - a11y: Not Assigned
> - ...

@rbuj @mate-desktop/core-team 

There are more things to do in general for mate-control-center, for example fixing deprecated widgets. ;)
- GtkTable (deprecated)
- GtkStyle (deprecated)
- glib2 deprecations
- many more..... in all projects.

I know nobody like to do this because it isn't a creation process.
I fixed a lot deprecations in the last years, but currently i am complete busy with reviewing/testing your PRs several hours per day.

Well, the day will come when gtk+-4 will knock mightily at MATE door...
.....but with having early gtk-3.0 deprecations any discussion about gtk4 is still useless....

**Comment by rbuj** [comment]
> Is there a chance to to call original author of this application to inform him about changes?

@zhuyaliang isn't the original author of all written code in time-admin. Compare:
- https://github.com/mate-desktop/mate-control-center/blob/master/capplets/time-admin/src/time-map.c
- https://github.com/mate-desktop/mate-control-center/blob/master/capplets/time-admin/src/time-zone.c

Screenshots: https://linuxconfig.org/how-to-change-timezone-on-ubuntu-18-04-bionic-beaver-linux#h8-change-timezone-from-gui

**Comment by raveit65** [comment]
> isn't the original author of all written code in time-admin. Compare:

But he is the one who brought this application in MATE, so he is the original author of the code in MATE for me.

**Comment by raveit65** [comment]
@zhuyaliang 
Are you interested to maintain mate-time-admin?
Than i can add you to m-c-c.

**Comment by zhuyaliang** [comment]
Of course, I would like to maintain mate-time-admin.I love open source

**Comment by rbuj** [comment]
> > isn't the original author of all written code in time-admin. Compare:
> 
> But he is the one who brought this application in MATE, so he is the original author of the code in MATE for me.

You're wrong. What about intellectual property?

**Comment by rbuj** [comment]
Recent intellectual property infringement example:
- https://github.com/mate-desktop/mate-control-center/pull/468/files
- https://github.com/zhuyaliang/time-admin/commit/fedf366e50da6880bc9e9cb511d6fc2b959fdb3b

**Comment by raveit65** [comment]
@zhuyaliang 
Invitation is sent. You have now write access and should receive notifications about PR and issues.

> You're wrong. What about intellectual property?

@rbuj 
Sigh, you don't want to understand me.....

**Comment by rbuj** [comment]
> Sigh, you don't want to understand me.....

https://github.com/mate-desktop/mate-control-center/pull/477

**Comment by zhuyaliang** [comment]
@rbuj  I think it would be more beautiful to add font color to some text.Is it because the text is not obvious in some particular topic?

**Comment by rbuj** [comment]
@zhuyaliang [GNOME HIG 2.32](https://developer.gnome.org/hig-book/hig-book-html-2.32.0.tar.gz) / hig-book-html-2.32.0/en/windows-alert.html
### Title Format
Alert windows have no titles.
```
gtk_window_set_title(GTK_WINDOW(dialog),("Message"));
```
### Alert Text
- Primary text: 

> ... pango markup: `<span weight="bold" size="larger">Primary Text</span>`

- Secondary text: 

> ... place it one text line height beneath the primary text using the default font size and weight.

**Comment by rbuj** [comment]
A translator reported how to translate "g_bus_get_sync" or "g_bus_proxy_new".

Please, review primary and secondary text on these alerts:
```
capplets/time-admin/src/main.c:         MessageReport(_("open file"),_("Create pid file failed"),ERROR);
capplets/time-admin/src/main.c:        MessageReport(_("write file"),_("write pid file failed"),ERROR);
capplets/time-admin/src/main.c:             MessageReport(_("open file"),_("open pid file failed"),ERROR);
capplets/time-admin/src/main.c:             MessageReport(_("read file"),_("read pid file failed"),ERROR);
capplets/time-admin/src/time-tool.c:        MessageReport(_("Set Time"),_("NTP synchronization has been started, the modification is invalid"),INFOR);
```
Please, review primary text on these alerts:
```
capplets/time-admin/src/main.c:        MessageReport(("Get Icon Fail"),Error->message,ERROR);
capplets/time-admin/src/main.c:        MessageReport(_("g_bus_get_sync"),error->message,ERROR);
capplets/time-admin/src/main.c:        MessageReport(_("g_bus_proxy_new"),error->message,ERROR);
capplets/time-admin/src/time-tool.c:    MessageReport(_("GetNtpState"),error->message,ERROR);
capplets/time-admin/src/time-tool.c:        MessageReport(_("Set time zone"),error->message,ERROR);
capplets/time-admin/src/time-tool.c:        MessageReport(_("Set Ntp sync"),error->message,ERROR);
capplets/time-admin/src/time-tool.c:        MessageReport(_("Set Ntp sync"),error->message,ERROR);
```

> An alert may contain both primary and secondary text. The primary text briefly summarizes the situation. The secondary text provides additional information.

https://developer.gnome.org/hig-book/2.32/windows-alert.html.en#alert-text

**Comment by zhuyaliang** [comment]
I recommend retaining ```SetLableFontType```，```SetLableFontType``` can set font size

**Comment by rbuj** [comment]
`void SetLableFontType(GtkWidget *Lable,int FontSzie,const char *Word)` becomes a [dead code](https://en.wikipedia.org/wiki/Dead_code). Why do you want to preserve it?

Test:
```shell
$ git grep SetLableFontType
```

**Comment by zhuyaliang** [comment]
No, I mean to preserve the functionality of this function.
such as 
```SetLableFontType（NtpSyncLabel，11，_（“ Ntp Sync：”））;```

**Comment by rbuj** [comment]
`SetLableFontType` is not necessary if we use an [UI file](https://github.com/mate-desktop/mate-control-center/tree/test-time-admin-ui) to define the View Component in a [MVC design pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller).

Captura de pantalla a 2019-06-24 10-34-34

**Comment by zhuyaliang** [comment]
Okay, since you're using UI files, ```SetLableFontTypel``` superfluous.Please resolve the conflict file.

**Comment by rbuj** [comment]
@zhuyaliang done

**Comment by rbuj** [comment]
To keep pretty git logs click on "rebase and merge" button.

**Comment by raveit65** [comment]
Not related to PR, but i found this warning in logs 
```
main.c:49:21: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    TimeAdmin *ta = (TimeAdmin *)data;
                    ^~~~~~~~~~~~~~~~~
1 warning generated.
  CC       time-tool.o
  CC       time-zone.o
time-zone.c:353:5: warning: Potential leak of memory pointed to by 'db'
    g_ptr_array_foreach (db->locations, (GFunc) LoadCities, ta->CityListStore);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
time-zone.c:648:12: warning: Potential leak of memory pointed to by 'tz_info'
    offset = tz_info->utc_offset;
    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
```

**Comment by zhuyaliang** [comment]
@raveit65 I have found a solution to this warning. i can be repaired in a minute.

**Comment by zhuyaliang** [comment]
It's time to merge this Pr.

**Comment by sc0w** [comment]
@raveit65  I already reported it here https://github.com/mate-desktop/mate-control-center/pull/456#issuecomment-502064048

**Pull request merged**
