### PR TITLE
[ci] add gla11y in docker container

### PR DESCRIPTION
**Pull request by yetist**
Let us see what happen.

### CODE REVIEW

**Comment by sthibaul** [comment]
It seems to be going well, except a missing cleanup, I have submitted https://github.com/mate-desktop/mate-control-center/pull/473 for that

**Comment by sthibaul** [comment]
I'd say that, like compiler warnings and errors, we'd better go with taking a tagged snapshot, like
https://github.com/hypra/gla11y/blob/v0.2/gla11y
so that if gla11y introduces new fatals in its master branch, the mate-control-center CI won't suddenly break.

**Comment by sthibaul** [comment]
Also, to have better line number reporting, it'd be useful to add the python-lxml dependency.

**Comment by yetist** [comment]
I think it's ready to go now.

**Comment by sthibaul** [comment]
It looks good indeed. Perhaps you could even remove the existing `$(GLA11Y_OUTPUT)` from CLEAN, as the attached patch does: 
[patch.txt](https://github.com/mate-desktop/mate-control-center/files/3318581/patch.txt)

**Comment by yetist** [comment]
@sthibaul 

Done, thanks. 5781cdb

**Comment by yetist** [comment]
Squash the commits into one.

**Pull request merged**
