### PR TITLE
re-work of font viewer

### PR DESCRIPTION
**Pull request by raveit65**
I finished all the work a while ago at 30 Aug 2015 here at https://github.com/raveit65/mate-control-center/commits/dev-font-viewer-gtk3
So please don't ask me about details why i used a commit, i have forgotten it.  ;-)
I started with a port to sushi font loader to fix https://github.com/mate-desktop/mate-control-center/issues/143
Than i back ported more and more commits from upstream.
I used them since the beginning for the gtk3 testing repo for fedora and with f25 for official builds.
And i got no negative feedback.
@lukefromdc 
Please test it too

### CODE REVIEW

**Comment by lukefromdc** [comment]
I just tested it, seems to work fine and give good detail of font smoothing differences

**Comment by monsta** [comment]
Wow, that's really huge. Basically, it's a new app. At least it would be so for most users who probably never even knew about mate-font-viewer (due to ```NoDisplay=true```). I wonder if we should really go this way and copy all the new functionality from gnome-font-viewer...

**Comment by raveit65** [comment]
Why?
Having a overview window with all installed fonts is a improvement for me.

**Comment by flexiondotorg** [comment]
I'd like to see the improved font viewer land and also think it should be made visible in the menus.

**Comment by raveit65** [comment]
I squashed the sync with Sushi commits in one like suggested in irc.
Squashing the last sync commit isn't possible without editing a bunch of files.

**Comment by raveit65** [comment]
Now i squashed the gd-main-toolbar commits.

**Comment by raveit65** [comment]
Ok, i wouldn't squash more commits.

**Pull request merged**
