### PR TITLE
libslab: fix search icon misaligned

### LINKED ISSUE #299: search icon misaligned
#### MATE general version
1.18

#### Package version
1.18.2-2

#### Linux Distribution
Fedora 26

the search icon (inside the search input box, on the right side) is not aligned properly (affects all themes):
mate-control-center-search-icon

it should be vertically centered

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/48026135-search-icon-misaligned?utm_campaign=plugin&utm_content=tracker%2F559197&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F559197&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by zhangxianwei8**
Make use GtkSearchEntry instead of builtin NldSearchEntry
fixes #299

Signed-off-by: Zhang Xianwei <zhang.xianwei8@zte.com.cn>

### CODE REVIEW

**Comment by zhangxianwei8** [comment]
I have updated the patch to fix build warnings. Please review again? Thanks:)  @raveit65 @monsta @lukefromdc @sc0w

**Comment by lukefromdc** [comment]
Found a bad icon in my icon theme: it was a white "edit-find" icon in 16x16. Fixing that fixed my problem, this seems ready to go

**Comment by raveit65** [comment]
Thanks

**Comment by monsta** [comment]
Ah, I missed the warnings. Ok, it can be actually done simpler. The search entry widget is always used as `GtkEntry`, so it makes sense to store it as that type. Here: https://github.com/mate-desktop/mate-control-center/commit/172e05f957cfcf4b94c469f9b0933ce414faaf8a

**Pull request merged**
