### PR TITLE
appearance: Add file chooser settings

### PR DESCRIPTION
**Pull request by rbuj**
Related issue https://github.com/mate-desktop/pluma/issues/586
Do not merge before #591

Captura de pantalla a 2020-11-23 10-21-14

### CODE REVIEW

**Comment by mbkma** [comment]
These settings are already configurable in mcc->File Management, caja->preferences and from Caja->view.

**Review by lukefromdc — APPROVED** [review]
This works well and adds a much-needed feature. Anyone without deconf-editor installed or who does not know how to use it cannot easily change these settings without this. Code looks clean, and we unref the new filechooser settings same way as the other settings when we are done. Nice work

**Comment by cwendling** [comment]
> Anyone without deconf-editor installed or who does not know how to use it cannot easily change these settings without this.

Actually, as mentioned in https://github.com/mate-desktop/pluma/issues/586 all these settings are available in the right-click menu of the GTK file chooser.

This said, it kind of make sense to have this in the preferences.
However, I feel the "preview" section now looks weird, because it's not affected by the file chooser settings.  Maybe reorder the file chooser settings last? Not sure, but as is it looks odd to me.

**Comment by rbuj** [comment]
The merge conflict has been resolved.

**Comment by lukefromdc** [comment]
Is this ready to go or does it need more work?

**Comment by rbuj** [comment]
Yes, it can now be merged once it's approved.

**Comment by raveit65** [comment]
m-c-c depends now now on a gsettings schema `org.gtk.Settings.FileChooser` from a third party application.
Is this part of gtk itself or gnome-desktop-schemas ?
To be sure that it is always installed.

**Comment by rbuj** [comment]
gtk
```
$ rpm -qf /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
gtk3-3.24.23-1.fc33.x86_64
```

**Comment by raveit65** [comment]
Hmm, why are those new entries under `Menus&Toolbars?
Bildschirmfoto zu 2020-11-28 18-27-02
I would prefer them under `File Chooser` like it was in screenshot of first post.
They have nothing to do with the toolbar or menus, ihmo.

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
Thanks, that better :) 

> However, I feel the "preview" section now looks weird, because it's not affected by the file chooser settings. Maybe reorder the file chooser settings last? Not sure, but as is it looks odd to me.

I am undecided.
From logical point it makes sense to sort `File Chooser` section to the bottom of the dialog.
But from optical point of view i think it looks nicer when `Preview` section is at the bottom, because the preview use the whole width of the dialog.
This should you decide guys :)

**Review by raveit65 — APPROVED** [review]
Works fine.

**Comment by lukefromdc** [comment]
I just verified that GTK 3 source code includes the file org.gtk.Settings.FileChooser.gschema.xml

**Comment by lukefromdc** [comment]
I also agree this does NOT belong under "menus and toolbars," why was it moved there? Looks like an error, as there are TWO "menus and toolbars" sections in that screenshot, second one contains only filechooser settings

**Pull request merged**
