### PR TITLE
appearance: use mate_image_menu_item replace gtk_image_menu_item

### PR DESCRIPTION
**Pull request by zhuyaliang**
Replace the deprecated ```gtk_image_menu_item``` in ```GTK3``` with the ```mate_image_menu_item``` provided by __mate-desktop__

### CODE REVIEW

**Comment by raveit65** [comment]
`MATE_DESKTOP_REQUIRED=1.25.0` in configure.ac needs to be updated.

**Comment by zhuyaliang** [comment]
@raveit65 The problem has been fixed

**Comment by raveit65** [comment]
Menu entries are looking the same compare with 1.26 in a VM (left with new menu, right with 1.26)
mcc-menus_cut

**Review by raveit65 — APPROVED** [review]
LGTM

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine here too. Menu items in mate-appearance-properties "interface" tab look the same as before.

**Pull request merged**
