### PR TITLE
libslab: avoid deprecated g_type_class_add_private

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by raveit65** [comment]
I am a little bit afraid to test this when i get a segfault. Any progress?

**Comment by raveit65** [comment]
Indeed a segfault.
```
[root@mother rave]# mate-control-center 
Segmentation fault (core dumped)
```

**Comment by yetist** [comment]
`bookmark-agent.c` is very different, so keep it use the origin code.

**Comment by raveit65** [comment]
Segfault is gone. I will squash both commits.

**Pull request merged**
