### PR TITLE
Add meson build support

### PR DESCRIPTION
**Pull request by zhuyaliang**
## test meson
```
meson setup _build --prefix=/usr 
ninja -C _build

DESTDIR=/tmp/meson_dir meson install -C _build
```
## test make
```
 ./autogen.sh --prefix=/usr 
make

make install DESTDIR=/tmp/make_dir
```

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
Had to configure with
`meson setup build  --prefix=/usr -Daccountsservice=false`
as I do not use accountservice and know little of it. This should
have been autodetected and was not. Default is set to true in meson_options.txt
if it were set to auto this would not be a problem
Build then completed, but a schema was installed under the wrong name, giving a 
failure to run:

`(mate-control-center:40666): GLib-GIO-ERROR **: 23:55:36.882: Settings schema 'org.mate.control-center' is not installed`

in /usr/share/glib-2.0/schemas 
I got 
`org.mate.control-center.gschema.xml.in`
instead of 
`org.mate.control-center.gschema.xml`

**Comment by zhuyaliang** [comment]
@lukefromdc Please delete ```/etc/xdg/auto start/matecc.menu```

**Comment by zhuyaliang** [comment]
Please test again

**Review by lukefromdc — APPROVED** [review]
As of the latest changes, the meson build works fine, and with accountsservice not installed  accountsservice is automatically disabled in configuration

**Comment by raveit65** [comment]
Mime dir is at the wrong place and a lot of files are missing. Please use your own installation instructions and compare.
```
[rave@mother ~]$ ls -la /tmp/meson_dir/usr/mime/
insgesamt 0
drwxr-xr-x 3 rave rave  60 21. Dez 16:20 .
drwxr-xr-x 7 rave rave 140 21. Dez 16:20 ..
drwxr-xr-x 2 rave rave  60 21. Dez 16:20 packages
```
```
[rave@mother ~]$ ls -la /tmp/make_dir/usr/share/mime/
insgesamt 32
drwxr-xr-x  4 rave rave 320 21. Dez 16:27 .
drwxr-xr-x 14 rave rave 280 21. Dez 16:27 ..
-rw-r--r--  1 rave rave   0 21. Dez 16:27 aliases
drwxr-xr-x  2 rave rave  60 21. Dez 16:27 application
-rw-r--r--  1 rave rave   0 21. Dez 16:27 generic-icons
-rw-r--r--  1 rave rave 131 21. Dez 16:27 globs
-rw-r--r--  1 rave rave 134 21. Dez 16:27 globs2
-rw-r--r--  1 rave rave   0 21. Dez 16:27 icons
-rw-r--r--  1 rave rave  12 21. Dez 16:27 magic
-rw-r--r--  1 rave rave 244 21. Dez 16:27 mime.cache
drwxr-xr-x  2 rave rave  60 21. Dez 16:27 packages
-rw-r--r--  1 rave rave  62 21. Dez 16:27 subclasses
-rw-r--r--  1 rave rave  16 21. Dez 16:27 treemagic
-rw-r--r--  1 rave rave  33 21. Dez 16:27 types
-rw-r--r--  1 rave rave   4 21. Dez 16:27 version
-rw-r--r--  1 rave rave   0 21. Dez 16:27 XMLnamespaces
```

**Comment by raveit65** [comment]
The rest of the installation is the same as with autotools.
Function of applications aren't tested because i do not use meson for my RPMs for fedora.
I am to lazy to rewrite my spec files :-)

**Comment by zhuyaliang** [comment]
Need to run  ```update-mime-database -V /tmp/meson_dir/usr/share/mime/ ``` update mime data,I have added ```meson_post_istall. py```, and the mime data will be updated after the installation is completed

**Comment by raveit65** [comment]
Not sure if this is a good idea to add meson_post_install.py, because all this commands `glib-compile-schemas`, 'gtk-update-icon-cache' and 'update-mime-database` are done with rpm package installation process. So this is a double action. I am sure debian and archlinux packaging do the same.

**Comment by raveit65** [comment]
Btw. the script itself might be OK. But should this be called by meson.build?

**Comment by raveit65** [comment]
After running `update-mime-database -V /tmp/meson_dir/usr/share/mime/` the mime data are the same as with autotools. Also the mime datadir are the same now.
I thought you wants to run the meson_post_install.py with meson.build ?
This didn't happen here and i am fine with it.

**Comment by lukefromdc** [comment]
The package should be installable directly with `ninja -C build install` in which case we then need to recompile schemas from the build system as the packaging system is bypassed.

**Comment by raveit65** [comment]
I tested it again and mine dir are the same after running `update-mime-database -V /tmp/meson_dir/usr/share/mime/`.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
