### PR TITLE
A much more organised categorisation of Control Center items.

### PR DESCRIPTION
**Pull request by flexiondotorg**
This organisation of categories has been well tested in Ubuntu MATE and makes use of all the available categories with no items being duplicated.

### CODE REVIEW

**Comment by flexiondotorg** [comment]
These changes have also been tested on Linux Mint MATE 17.2.

**Comment by flexiondotorg** [comment]
Any feedback for this? @infirit, @monsta @NiceandGently

**Comment by monsta** [comment]
After the last commit I see all categories translated to Russian, so I don't mind :smile:

**Comment by monsta** [comment]
Also we'd probably want @clefebvre's confirmation :smile:

**Comment by NiceandGently** [comment]
I don't care very much if 'System' is renamed to 'Administration'. Maybe it's a better name for it.
+1

**Comment by infirit** [comment]
Ok, so I don't see any of the problems like duplicate entries that this is fixing. But I do when the other commit, https://github.com/mate-desktop/mate-control-center/pull/197, is applied some things do end up in other. However I never had anything duplicate in the menu's before.

However, if this fixes issues for other ppl and it does not regress on my end, so I have no objection to this. But please update the commit message with what this is supposed to solve :smile:.

**Comment by infirit** [comment]
I found a problem, the control-center application does not yet reflect these change.

**Comment by monsta** [comment]
Rebased and merged, thanks :smile:

**Pull request closed without merging**
