### PR TITLE
Migrate from dbus-glib to GDBus

### PR DESCRIPTION
**Pull request by yetist**
mate-appearance-properties: capplets/appearance/theme-util.c

How to test:
1. Get a theme file.
2. Install the theme by click the `Install...` button on the `mate-appearance-properties` UI.
3. If the theme require a gtk-engine that didn't installed on your system, it will install a package that include the engine file by PackageKit.

I don't have a valid gtk-2.0 theme to test it.

### CODE REVIEW

**Comment by sc0w** [comment]
clang warnings:

```
theme-util.c: In function 'theme_install_file':
/usr/include/glib-2.0/glib/gmacros.h:325:15: warning: 'return' with a value, in function returning void
 #define FALSE (0)
               ^
theme-util.c:267:12: note: in expansion of macro 'FALSE'
     return FALSE;
            ^~~~~
theme-util.c:239:6: note: declared here
 void theme_install_file(GtkWindow* parent, const gchar* path)
      ^~~~~~~~~~~~~~~~~~
theme-util.c:267:5: error: void function 'theme_install_file' should not return a value [-Wreturn-type]
    return FALSE;
    ^      ~~~~~
```

and fedora build in travis fails (I don't know why)

**Comment by raveit65** [comment]
Deployment failed for some reasons in at the end of fedora build.
But it was fine 8 days ago, see release page.
https://github.com/mate-desktop/mate-control-center/releases

**Comment by raveit65** [comment]
```
Deploying application
Initialized empty Git repository in /tmp/d20190430-5043-1llfzib/work/.git/
Switched to a new branch 'gh-pages'
cd -
cd /tmp/d20190430-5043-1llfzib/work
rsync: send_files failed to open "/home/travis/build/mate-desktop/mate-control-center/html-report/2019-04-30-071702-575-1@fd41cc02e556_gdbus/failures/clang_other_error_b_wVg4.i.stderr.txt": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
Could not copy /home/travis/build/mate-desktop/mate-control-center/html-report.
failed to deploy
```

**Comment by sc0w** [comment]
warnings fixed, and travis is ok, thanks

**Pull request merged**
