### PR TITLE
keybindings: Allow to select an installed application through a dialog

### PR DESCRIPTION
**Pull request by cwendling**

### CODE REVIEW

**Comment by cwendling** [comment]
@lukefromdc Open the *Keyboard Shortcuts* control center "applet", either through *System → Preferences → Hardware → Kayboard Shortcuts* or the same through the *Control Center*.  Then, click the *Add* button, and see you now got a *Browse applications…* button next to the *Command* field.  Click on it and have fun :)

**Comment by lukefromdc** [comment]
The dialog comes up fine, this seems to be ready to go and is a nice change

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-control-center/commit/5d928407022afa0fd9e1c6798f4c93ba54418b4e
Thank you

**Comment by monsta** [comment]
Looks like ```mnemonic_widget``` for the command label is lost after this...

**Comment by monsta** [comment]
Also the new button doesn't have a mnemonic, or did I miss it?

**Comment by cwendling** [comment]
@monsta Oops, how did I miss that.  Sorry, will fix now.

**Comment by monsta** [comment]
No problem, it just needs a quick fix :slightly_smiling_face:

**Comment by monsta** [comment]
I'll test the fix in https://github.com/mate-desktop/mate-control-center/pull/277.

**Pull request closed without merging**
