### PR TITLE
use offscreen windows for previews

### PR DESCRIPTION
**Pull request by dnk**
gtk 2.20+ provides offscreen window. use them for previews
minor fixes

### CODE REVIEW

**Comment by dnk** [comment]
there are still problems on gtk3 with theme previews :(

**Comment by dnk** [comment]
now mate-appearance-properties correctly display previews event if thumbnails (~/.cache/thumbnails/normal/) are missing

**Comment by raveit65** [comment]
It works with gtk3, but after cleaning the cache it creates only one thumbnail for one theme in cache directory, means i need to re-open mate-appearance-properties about 10 times for that all thumbnails are created. but maybe something is wrong with the resulting patch from this PR.
Anyways, great work :)

**Comment by monsta** [comment]
I'd leave stock buttons as is even though they're considered deprecated since 3.10. I vote for using them until gnome guys really remove them from the code.
Besides, it will save us a new line in ```po/POTFILES.in```. Currently the build **breaks** because there are new translatable lines but this file isn't listed in ```po/POTFILES.in```:

```
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.

capplets/common/theme-thumbnail.c
```

**Comment by monsta** [comment]
Ok, and after removing these ```#if```s for stock buttons, I can confirm the weirdness @raveit65 reported:

> after cleaning the cache it creates only one thumbnail for one theme in cache directory, means i need to re-open mate-appearance-properties about 10 times for that all thumbnails are created.

And it's only in the main mate-appearance-properties window. As for the Customize Theme dialog, no thumbnails are created there at all. Controls, Colors, Window Border, Icons - all show only question marks, no matter how many times I restart the app. :disappointed:

**Comment by monsta** [comment]
Hmm... tried this PR with GTK+2 build as well... decided to clean the cache here too - to see what will happen. Well it was even worse... not only Customize Theme dialog, but also the main mate-appearance-properties window has only question marks now. Restarting the app doesn't help.

Did I do something wrong? :confused:

**Comment by monsta** [comment]
Closing as it really needs more work - for both GTK+ builds :confused:

**Pull request closed without merging**
