### PR TITLE
time-admin: Remove po-timezones

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
I love distcheck :)
https://travis-ci.org/mate-desktop/mate-control-center/jobs/546343335#L3220

**Comment by zhuyaliang** [comment]
@rbuj Time zone files are fixed. I don't think we need to generate translated documents dynamically.We can make full use of the existing documents. ```system-config-date```

**Comment by rbuj** [comment]
[system-config-date](https://src.fedoraproject.org/rpms/system-config-date) package not actively developed anymore.

**Comment by rbuj** [comment]
@raveit65 I think it's fixed now.

**Comment by zhuyaliang** [comment]
@rbuj 
Yes, but we don't need to introduce a new file at all.I can provide mate-c-c-timezones.pot, which is the original file for the time zone

**Comment by raveit65** [comment]
> I think it's fixed now.

No, see checks, you need https://github.com/mate-desktop/mate-control-center/commit/a33c70dff7dc6ec409b9afaa7caa19c318d7ed9e
Or better do a rebase from master.


Btw. Does mate-time-admin work with timezones from tzdata if installed?
Please have a discussion.

**Comment by rbuj** [comment]
@zhuyaliang For instance, Evolution has its own [l10n file for time zone names](https://github.com/GNOME/evolution/blob/master/src/calendar/zones.h), neither uses the system-config-date po file, nor adds a new translation domain for time zone names.

**Comment by zhuyaliang** [comment]
@rbuj I reference to gnome-c-c's datetime, which uses ```system-config-date```
[https://github.com/GNOME/gnome-control-center/blob/master/panels/datetime/po-timezones/README](url)
This will reduce our maintenance workload.Of course I respect your change.Take a look at the opinions of others.
@yetist @raveit65

**Comment by rbuj** [comment]
It's just a git rebase master.

**Comment by raveit65** [comment]
Selection of cities is very limited.
For Germany i find only Berlin. I would expect to select other German big cities too, eg. Hamburg, Frankfurt or Munich.
But this seems to be a prob with previous version too.

Honstly, i won't decide which version will be used .
I have rebuild m-c-c to much last weeks, i am tired of this.....

**Comment by raveit65** [comment]
Ok, it seems that only really big countries with several timezones have more than one city listed in timezone data. It's the same in both versions.

- translations from po-timezones are from 2010, latest timezone from tzdata are from 2019.
- tzdata is a very basic package in linux and bsd, so timezone data will always be updated.
- less code to maintain
- no extra translation domain at transifex.
- it seems to be working in a quick test.

But maybe i missed an important advantage if using a own timezone data?

**Comment by yetist** [comment]
@rbuj 

Is it possible to merge existing translations of timezone locally and push the translations to transifex to save translators time?

**Comment by raveit65** [comment]
> Is it possible to merge existing translations of timezone locally and push the translations to transifex to save translators time?

Why you want translate it ? when using 
```
[root@mother rave]# ls /usr/share/zoneinfo/
Africa      Chile    GB         Indian       Mexico    posixrules  Universal
America     CST6CDT  GB-Eire    Iran         MST       PRC         US
Antarctica  Cuba     GMT        iso3166.tab  MST7MDT   PST8PDT     UTC
Arctic      EET      GMT+0      Israel       Navajo    right       WET
Asia        Egypt    GMT-0      Jamaica      NZ        ROC         W-SU
Atlantic    Eire     GMT0       Japan        NZ-CHAT   ROK         zone1970.tab
Australia   EST      Greenwich  Kwajalein    Pacific   Singapore   zone.tab
Brazil      EST5EDT  Hongkong   leapseconds  Poland    Turkey      Zulu
Canada      Etc      HST        Libya        Portugal  tzdata.zi
CET         Europe   Iceland    MET          posix     UCT

```

**Comment by raveit65** [comment]
> Is it possible to merge existing translations of timezone locally and push the translations to transifex to save translators time?

And yes, it is possible to add local .po files to transifex.
Than the resource will show existing translations at transifex website , and Translators don't need to translate it again.

**Comment by yetist** [comment]
> Why you want translate it ? when using
> 
This file needs to be translated again:
https://github.com/mate-desktop/mate-control-center/blob/db8dc184756b1f23406222dd46a260519341983c/capplets/time-admin/src/time-zones.h

**Comment by rbuj** [comment]
Sample code for importing translations from gnome-control-center to tx:
```shell
#!/bin/bash
tx pull -a

./autogen.sh --prefix=/usr
make -C po mate-control-center.pot
sed -i 's/PACKAGE VERSION/MATE Desktop Environment/g' po/mate-control-center.pot
make -C po update-po
mv po/mate-control-center.pot .
cd po
for f in *.po; do
  lang=${f%.*};
  msgunfmt /usr/share/locale/$lang/LC_MESSAGES/gnome-control-center-2.0-timezones.mo -o gcc_$lang.po;
  if [ -f "gcc_$lang.po" ]; then \
    msgmerge gcc_$lang.po $f > $lang.aux;
    rm -f gcc_$lang.po;
    mv $lang.aux $f
  fi;
done

tx push -s -t
```

Based on system-config-date/f24/system-config-date-1.10.9/po/Makefile:
```
%.mo: %.po
	$(MSGFMT) -o $@ $<

# stub: grab timezone comments from anaconda translations
#       if anaconda translations found it merged with zone.tab strings to
#       produce only timezone translations. 
	@lang=`basename $< .po` ; \
	msgunfmt /usr/share/locale/$$lang/LC_MESSAGES/anaconda.mo -o anaconda_$$lang.po ;\
	included_timezone_po="" ;\
	if [ -f "anaconda_$$lang.po" ]; then \
	  included_timezone_po="$$lang.timezone.po" ;\
	  cat /usr/share/zoneinfo/zone.tab | cut -f4 | grep "^[a-zA-Z]" | sort -u |\
	  while read line; do echo -e "\n#. generated from zone.tab\nmsgid \"$$line\"\nmsgstr \"\""; done |\
	  msgmerge anaconda_$$lang.po - > $$included_timezone_po ;\
	fi; \
	\
	if [ -f "timezones/$<" ]; then \
		msgcat --use-first $< timezones/$< $$included_timezone_po ; \
	else \
		msgcat --use-first $< $$included_timezone_po; \
	fi | msgfmt --check -o $@ - ; \
	\
	if [ -f "$$included_timezone_po" ] ; then rm -f $$included_timezone_po; fi; \
	if [ -f "anaconda_$$lang.po"     ] ; then rm -f anaconda_$$lang.po;     fi;
```

**Comment by raveit65** [comment]
> This file needs to be translated again:
https://github.com/mate-desktop/mate-control-center/blob/db8dc184756b1f23406222dd46a260519341983c/capplets/time-admin/src/time-zones.h

Ok, this will be include in normal mate-control-center.pot, but we don't need to add an extra translation domain to transifex.

**Comment by raveit65** [comment]
@rbuj 
Can you import the translation to transifex when we merge this?

@zhuyaliang
 Do you agree with doing at in this way?

**Comment by zhuyaliang** [comment]
@raveit65  I have no objection.

**Comment by rbuj** [comment]
@raveit65 I will do it.

**Comment by rbuj** [comment]
The merge conflict is fixed now.

**Pull request merged**
