### PR TITLE
Use themes' icons for mate-time-admin

### PR DESCRIPTION
**Pull request by yetist**
Modify the icons to use transparent background, and rename the icon name from `mate-times-admin.png` to `mate-time-admin.png`.

image

### CODE REVIEW

**Comment by zhuyaliang** [comment]
@yetist Thank you for your change. It looks much more beautiful

**Comment by rbuj** [comment]
@yetist

I think that you can use [oxygen icons](http://www.iconarchive.com/show/oxygen-icons-by-oxygen-icons.org/Apps-preferences-system-time-icon.html), and you can also add [authors.txt](http://www.iconarchive.com/icons/oxygen-icons.org/oxygen/authors.txt) in capplets/time-admin/data/hicolor folder.

**Comment by yetist** [comment]
@rbuj 

Good, oxygen icon is better, but I think we should use theme's icon named `preferences-system-time`, and the `mate-icon-theme` seem lost this icon.

```
$ find /usr/share/icons/ -name "preferences-system-time*"|wc -l
35
$ find mate-icon-theme/ -name "preferences-system-time*"
mate-icon-theme/mate/scalable/apps/preferences-system-time-symbolic.svg
```

**Comment by yetist** [comment]
Now `mate-icon-theme` need to add `prefereces-system-time` svg and png icons.

**Comment by yetist** [comment]
On my system, now it fallback to use `hicolor` theme's icon, the icon file provides by gnome-control-center.
image

**Comment by raveit65** [comment]
Honestly, i prefer the origin icon with transparent background.
This looks much better than every preferences-system-time icon in my icon folder or from gnome.
But do what you like, i don't mind.......

**Comment by lukefromdc** [comment]
Here's what the original icon looks like with the white background removed:

mate-times-admin

**Comment by lukefromdc** [comment]
Than I propose we merge this and add the new icon to mate-themes

**Comment by rbuj** [comment]
Missing icon in titlebar window for Time Zone Selection dialog.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-icon-theme/pull/38
This will add missing icons to mate-icon-theme. I chooses original icons with transparant background from this PR, which looks very nice.

**Comment by raveit65** [comment]
Sadly, using the original icon with transparent background from https://github.com/mate-desktop/mate-icon-theme/pull/38 doesn't looks very sharp with HIDPI resulution.
Bildschirmfoto zu 2019-06-20 10-13-12

I will try now the oxygen icons.

**Comment by yetist** [comment]
@raveit65 

Thank you for rebase and squash that.

**Pull request merged**
