### PR TITLE
theme-installer.c: add tips when reinstall a existed theme

### PR DESCRIPTION
**Pull request by zhangxianwei8**
When ~/.themes/theme-name is existed, reinstalling the same theme will be failed. Add tips when reinstall a existed theme to fix it. This mentioned in #322.

##Steps to reproduce the behaviour##
cd /usr/share/themes (root user)
tar zcvf Menta.tar.gz Menta
Open m-a-p →Choose the "Menta" theme to delete
Click  "Install..." → choose "/usr/share/themes/Menta.tar.gz"
Rechoose "/usr/share/themes/Menta.tar.gz" to install again
It will be failed with tips: Installation for theme "Menta" failed. Can't move directory over directory
@raveit65 @lukefromdc

### CODE REVIEW

**Comment by raveit65** [comment]
We are in freeze for 1.20 for translations updates, so we can't merge this now, probably after release.

**Comment by zhangxianwei8** [comment]
When will the 1.20 be released?

**Comment by raveit65** [comment]
End of this month.

**Comment by zhangxianwei8** [comment]
That's OK. Thanks.
I have joined MATE translation TEAM. How can I contribute to it?

**Comment by raveit65** [comment]
We use transifex for translations.
After 1.20 release we can merge this commit for example.
Than we need to update the mate-control-center.pot file at transifex.
At this point translators see new untranslated strings and can translate them.
After a while and if translations are done we can download new translations and make a new release.
Did you joined at transifex side to the team?
https://www.transifex.com/
https://www.transifex.com/mate/MATE/dashboard/

**Comment by sc0w** [comment]
@zhangxianwei8 please, can you avoid the deprecated GtkStock?

I think you can use:

```
		gtk_button_set_image (GTK_BUTTON (apply_button),
					  gtk_image_new_from_icon_name ("gtk-apply",
								GTK_ICON_SIZE_BUTTON));
```

instead:
```
		gtk_button_set_image (GTK_BUTTON (apply_button),
					  gtk_image_new_from_stock (GTK_STOCK_APPLY,
								GTK_ICON_SIZE_BUTTON));
```

**Comment by zhangxianwei8** [comment]
Yes, I joined at transifex site to the team two days ago.@raveit65
I'll try to use new function. Oh, there's some other deprecated functions, should be fixed?@sc0w

**Comment by raveit65** [comment]
@zhangxianwei8 
You're welcome.

About handling deprecated GtkStock in buttons and menu-entries in general.
Icons in buttons and menus are a typical sign that you're using MATE-Desktop and not gnome-shell or cinnamon.
So, we decided a while ago to ignore deprecations warnings in old code about and we want to use the deprecation until we switch to Gtk4, if this ever will happen.
Well, there are ways to fix them, ie. with a horizontal GtkBox or with a GtkGrid inside the button.
But this is a lot of work if you like to do this, but this isn't really needed at the moment.
If it is possible to fix them easy and without removing the icons you can do it......
But honestly, there are other deprecations in m-c-c code which are more important to fix.
Ie. GtkStyle or GtkTable code or glib stuff.
We started 2-3 years ago to fix deprecations all over the code, but is seems to be a never ending story. ;-)

**Comment by sc0w** [comment]
@zhangxianwei8 in this PR I only see that warning, so it is enough, I like to see no deprecations if possible in new code :)

Please test if my fix works with the icon image

**Comment by zhangxianwei8** [comment]
I use gtk_image_new_from_icon_name instead of gtk_image_new_from_stock. It works, no new warning. @sc0w

**Comment by zhangxianwei8** [comment]
I'll try to fix some more important deprecations. @raveit65

**Comment by sc0w** [comment]
capplets/appearance/theme-installer.c **100644 → 100755** <- @zhangxianwei8

**Comment by zhangxianwei8** [comment]
Fixed :) @sc0w

**Comment by zhangxianwei8** [comment]
Hi, @raveit65 when  do you update the mate-control-center.pot file at transifex usually? I haven't seen any change at transifex until now.

**Comment by raveit65** [comment]
Normal i do that directly after a commit changes a translation.
But, i am thinking about to move transifex config to last stable branch.
So i am waiting with uploading new .pot sources at the moment.
All this needs to be discussed with the team.
Please give us some time.....

**Pull request merged**
