### PR TITLE
touchpad settings: add option to enable/disable touchpad

### PR DESCRIPTION
**Pull request by monsta**
fixes https://github.com/mate-desktop/mate-desktop/issues/178

### CODE REVIEW

**Comment by raveit65** [comment]
I can only test it with 1.10.x with my notebook.
Do i need more commits from 1.11, maybe from mate-settings-daemon?

**Comment by raveit65** [comment]
Ok, commit does not aplly out of box with 1.10.2
2 out of 4 hunks FAILED -- saving rejects to file capplets/mouse/mate-mouse-properties.ui.rej

**Comment by raveit65** [comment]
Added support for natural scrolling commit is also needed, but it looks like i need more from m-s-d.

**Comment by raveit65** [comment]
After applying a tons of patches i can say it works.
Same for the other new touchpad settings.

**Comment by monsta** [comment]
Yes... @clefebvre added some touchpad-related code in 1.11.x :smile:

**Pull request merged**
