### PR TITLE
fix some deprecations

### PR DESCRIPTION
**Pull request by monsta**
@raveit65 @lukefromdc please test for any possible issues :smile:

This is not a complete list of deprecations, I think it's only a half... I'll try to fix other ones some time later.

### CODE REVIEW

**Comment by raveit65** [comment]
Maybe use a define for deprecated 'gtk_{h/v}box_new', see https://github.com/mate-desktop/pluma/commit/9994dd399ab569d547e18cb5f01900f8db953312

**Comment by raveit65** [comment]
Or better change it in code to 'gtk_box_new (GTK_ORIENTATION_VERTICAL, 6);'
w/o ifdefs, and use a negative define for gtk2 build.
```
#if !GTK_CHECK_VERSION (3, 0, 0)
#define gtk_box_new(GTK_ORIENTATION_VERTICAL,Y) gtk_vbox_new(X,Y)
#endif
```
in result the code is ready for gtk3 and we need only to remove the define after transition to gtk3.
Something what i did here https://github.com/mate-desktop/caja/commit/7b5604b7e1af03445e7209b8a067ef359c2b4846
Maybe that works.

**Comment by lukefromdc** [comment]
I just tested this, everything works.

**Comment by lukefromdc** [comment]
The dev-libslab branch with all the changes is what I just tested. Good results with 
both GTK3.18 and GTK3.19.6, cycled through all the capplets, except of course that
compiz comes up unsupported in the window preferences same as before.

**Comment by raveit65** [comment]
Looks good so far. I tested the dev-libslab branch with both toolkit versions.
With gtk2 i see a change with the 'look and feel' of m-c-c main window :smile: 
Selecting a header at the left marked the whole group with a selected color.
m-c-c
With gtk3 build only the header of the selected group is marked with the selected clolor.

**Comment by lukefromdc** [comment]
In GTK3 3.18 on my systems the selected BG color is on the header both
with and without these changes, in GTK3.19.6 I got the selected FG
color on the header after the change, did not recheck that in GTK3.18

**Comment by raveit65** [comment]
Using a negative define does not work for gtk2 builds. I tested this with caja.
Here i get re-define warnings and some boxes are broken.

**Comment by lukefromdc** [comment]
One clarification: In gtk 3 I am getting the selected color on the text, not the background of the header

**Comment by monsta** [comment]
I've decided not to use the mentioned defines for boxes as I remember I've spent too much time doing search-and-replace in mate-system-monitor... Sure, it reduces the ifdef hell, but it's easier to simply delete the portions of code later :smile:

Marking the selected section with color always worked in GTK+2. In GTK+3 color selection is there for me, but it's in the wrong place - e.g. higher or lower than the actual section. But don't worry about the colors too much here: I didn't touch the corresponding code yet. :smile:

**Comment by monsta** [comment]
If everything is ok for you guys I'll merge this and then make a new PR from dev-libslab branch. That one changes the public API, so I've decided to separate it from the changes in this PR.

**Comment by raveit65** [comment]
well, see my screenshot with gtk2 build

**Comment by monsta** [comment]
I don't see anything unusual :smile:

**Comment by raveit65** [comment]
With gtk2 i see a change with the 'look and feel' of m-c-c main window :smile:
Selecting a header at the left marked the whole group with the selected color.

**Comment by raveit65** [comment]
Opps, soory for this noise, looks like this is normal behaviour.
Ok than everyting is fine

**Comment by monsta** [comment]
Ok, there goes https://github.com/mate-desktop/mate-control-center/pull/219.

**Pull request merged**
