### PR TITLE
default-applications: Add a widget for a default messenger application

### PR DESCRIPTION
**Pull request by rbuj**
### Setting Default Instant Messenger

Requires https://github.com/mate-desktop/mate-desktop/pull/393

Captura de pantalla a 2019-06-10 23-42-29

### Setting Instant Messenger Keybinding

Requires mate-desktop/mate-settings-daemon#278

Captura de pantalla a 2019-06-13 10-14-47

Fixes partially #443

### CODE REVIEW

**Comment by lukefromdc** [comment]
This should be tested by someone who has pidgen and ideally another messaging program installed. I do not

**Comment by sc0w** [comment]
@rbuj I think you need to edit the first post, with `"Fixes partially #443"` instead `"Partially fixes #443"`

If github reads `fixes #443` , the issue will be automatically closed when the PR is merged.

**Comment by rbuj** [comment]
@sc0w 
done

**Comment by rbuj** [comment]
@lukefromdc 
Test on Fedora 30:

Captura de pantalla a 2019-06-11 10-29-52

**Comment by vkareh** [comment]
@rbuj - this seems to work. I get Slack on my dropdown (but not Hexchat, since it doesn't have the `"InstantMessaging"` category). However, once I set it: then what? What's the purpose of this? It sets the new gschema, but nothing uses that as far as I know, and there's no `g_app_info_set_as_default_for_type` or any of that type of call, nor keyboard shortcut to launch an instant messenger client.

So I'm all for having this option, but maybe we should decide as a team what we are going to use it for

**Comment by vkareh** [comment]
@cwendling brings up a good point... the "user-available" icon would work better than the "user-idle" icon

**Comment by raveit65** [comment]
Why not taking the icon from im-chooser ?
Which matches perfectly the function of a messenger, with a keyboard connected to the world.
Bildschirmfoto zu 2019-06-12 17-55-40
png's can be found here https://pagure.io/im-chooser/blob/master/f/data
We can rename and add this to mate-icon-theme or better m-c-c directly.

**Comment by rbuj** [comment]
@raveit65 It looks great!

Captura de pantalla a 2019-06-12 19-00-42

**Comment by raveit65** [comment]
@vkareh 
Looks like icon scaling for HIDPI is missing here in that GUI?

**Comment by vkareh** [comment]
My question still remains: what does this feature do? What happens when I set a default messenger? What can I do with it?

**Comment by rbuj** [comment]
We can add a keybinding for messenger key, like calculator (https://github.com/mate-desktop/mate-settings-daemon/pull/255).

For instance some [Logitech media keyboards](http://moparx.com/2006/05/configuring-logitech-media-keyboard-elite-linux/) have messenger key (keycode 199 = XF86Messenger, for logiclx300 XkbModel).

**Comment by lukefromdc** [comment]
Icon looks fine to me

**Comment by rbuj** [comment]
It adds instant messenger keybinding into mate-keybinding-properties (keybinding editor).

**Comment by raveit65** [comment]
> My question still remains: what does this feature do? What happens when I set a default messenger? What can I do with it?

Correct question to a messenger dev would be why a messenger use a mimetype...... :)

**Comment by rbuj** [comment]
@raveit65 Setting up hexchat as the default handler for irc uri from command line:
```
$ rpm -ql hexchat | grep desktop
/usr/share/applications/io.github.Hexchat.desktop
$ cat /usr/share/applications/io.github.Hexchat.desktop | grep Mime
MimeType=x-scheme-handler/irc;x-scheme-handler/ircs;
$ xdg-mime default io.github.Hexchat.desktop x-scheme-handler/irc
$ xdg-open irc://irc.dal.net/
```

**Comment by raveit65** [comment]
> Would you like to add im mime types to m-c-c?

@rbuj 
Confused, i thought mate-default-applications checks already for mimetypes because @vkareh updated mimetypes for eom for this reason.

**Comment by raveit65** [comment]
@rbuj 
New keybinding is working but i get this warning in terminal when i try to change the keybinding for messenger.
```
[rave@mother ~]$ mate-keybinding-properties 

(mate-keybinding-properties:29385): GLib-GObject-CRITICAL **: 14:45:59.543: Object class EggCellEditableEventBox doesn't implement property 'editing-canceled' from interface 'GtkCellEditable'
```

**Comment by raveit65** [comment]
> Would you like to add im mime types to m-c-c?

@rbuj Yes , might be a good idea to see that messengers.

**Comment by rbuj** [comment]
> [rave@mother ~]$ mate-keybinding-properties 
> 
> (mate-keybinding-properties:29385): GLib-GObject-CRITICAL **: 14:45:59.543: Object class EggCellEditableEventBox doesn't implement property 'editing-canceled' from interface 'GtkCellEditable'

Issue https://github.com/mate-desktop/mate-control-center/issues/226

**Comment by rbuj** [comment]
@vkareh Instant Messengers combo box lists HexChat if available.
@raveit65 default icq/irc/ircs/sip/xmpp scheme handler.

Test: Set HexChat as the default Instant Messenger App and run the following command in a terminal:
```shell
$ xdg-open irc://irc.freenode.net/gcc
```
Not all Instant Messenger Apps are compatibles with URI schemes.

**Comment by monsta** [comment]
@rbuj: are you sure it's needed to set the mimetype handlers? Not all the messengers are multi-protocol. Telegram isn't, for example. It won't be able to handle the mimetypes that are set there in the code...

**Comment by rbuj** [comment]
@monsta I think it's useful setting this from a GUI, as command line it's not easy to use, or it's unknown for most users.
```shell
$ xdg-mime query default x-scheme-handler/icq
io.github.Hexchat.desktop
$ xdg-mime default pidgin.desktop x-scheme-handler/icq
$ xdg-mime query default x-scheme-handler/icq
pidgin.desktop

```
It could be an improvement to check if the application is compatible with the schema/filetype before to call each `g_app_info_set_as_default_for_type` in:
https://github.com/mate-desktop/mate-control-center/blob/1c3f59e6148fc1ed2a71da6c81d894191d90e64a/capplets/default-applications/mate-da-capplet.c#L66

**Pull request merged**
