### PR TITLE
Remove unused variable from capplet_notebook_scroll_event_cb

### PR DESCRIPTION
**Pull request by rbuj**
Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
Where did you see a warning about in log?

**Comment by rbuj** [comment]
@raveit65 yes, you can see it on debian build logs which use -Wunused-parameter 

https://travis-ci.org/github/mate-desktop/mate-control-center/jobs/703563330#L2438

```
capplet-util.c:174:91: warning: unused parameter 'window' [-Wunused-parameter]
capplet_dialog_page_scroll_event_cb (GtkWidget *widget, GdkEventScroll *event, GtkWindow *window)
```

**Comment by raveit65** [comment]
Damned, i forgot that.....
Confirmed, warning is gone.
Can you please such useful infos in PR (not commit message), next time, please?

**Comment by rbuj** [comment]
@raveit65 You're right, sometimes I forget to add it, sorry for the inconvenience.

**Pull request merged**
