### PR TITLE
Apparence: draw-background key bug

### PR DESCRIPTION
**Pull request by tamplan**
When 'org.mate.background draw-background' is false, mate-appearance-properties should hide the background page.

Done with this PR.

When mate-appearance-properties is launched with argument '-p background', the app exit with no message.

Hop this helps.

Regards

### CODE REVIEW

**Comment by rbuj** [comment]
I could not reproduce your problem.

Captura de Pantalla 2020-05-19 a les 13 52 55

**Comment by tamplan** [comment]
Have you test with the draw-background key to false? Without this PR.

**Comment by tamplan** [comment]
Need to commit to remove g_print test message... :)

**Comment by rbuj** [comment]
> Have you test with the draw-background key to false and without this PR?

This key determines whether msd can draw the background.
```
$ dconf dump /org/mate/desktop/background/
[/]
color-shading-type='solid'
draw-background=false
picture-filename=''
picture-options='wallpaper'
primary-color='rgb(39,88,126)'
secondary-color='rgb(98,127,90)'
show-desktop-icons=true
```
To prevent user to change the background you should lock background keys via dconf.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/desktop_migration_and_administration_guide/custom-default-values-system-settings

**Comment by tamplan** [comment]
> To prevent user to change the background you should lock background keys via dconf.
I don't want to lock background keys.

Try with:
- set 'org.mate.background draw-background' to FALSE
- reboot
- you have got a blank screen
- launch mate-appearance-properties
- you have a page with you can change properties for a background the system don't show!

I think this is a bug, right?

This PR hide the background page if 'org.mate.background draw-background' is FALSE.

**Comment by rbuj** [comment]
> > To prevent user to change the background you should lock background keys via dconf.
> > I don't want to lock background keys.
> 
> Try with:
> 
> * set 'org.mate.background draw-background' to FALSE
> * reboot
> * you have got a blank screen

No, the background was drawn as usual.

bg

**Comment by tamplan** [comment]
Sorry, i forgot to give you more informations if i read this https://github.com/mate-desktop/mate-control-center/issues/567, it will better.

Please retry again with 'org.mate.background show-desktop-icons' set to FALSE too.

There is another bug but this PR don't matter of it.

'org.mate.background show-desktop-icons' to FALSE + 'org.mate.background draw-background' to FALSE give blank background on next reboot.

**Comment by raveit65** [comment]
> This PR hide the background page if 'org.mate.background draw-background' is FALSE.

Why, this is a problem?
I don`t think that there is one user in the world who had both keys disable and use a black desktop :)
org.mate.background draw-background
org.mate.background show-desktop-icons

**Comment by tamplan** [comment]
> > This PR hide the background page if 'org.mate.background draw-background' is FALSE.
> 
> Why, this is a problem?
> I don`t think that there is one user in the world who had both keys disable and use a black desktop :)
> org.mate.background draw-background
> org.mate.background show-desktop-icons

I think no too.
But, in my opinion, when a thing is disabled i don't see a reason to purpose to change properties about it and so, when org.mate.background draw-background is FALSE, there is no reason to purpose to user to change properties about a background not shown.

**Comment by tamplan** [comment]
It seems i can purpose more than one PR at the same time even if there are on 2 different branches.
Travis can understand the previous PR i made is not related with this one...

**Pull request closed without merging**
