### PR TITLE
time-admin: Fix license notice in time-zone.h|c, time-map.h|c

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@zhuyaliang 
Can you please use the `rebase+ merge` button to avoid this needless merge commit?
https://github.com/mate-desktop/mate-control-center/commit/dcadc0ec7ce7ec5a7f4b42a6b07ee76922ba5569
You can change that in the dropdown-menu of the button.

**Comment by raveit65** [comment]
Same for other merged PRs.
Now we have a lot of needless merge commits. :/
https://github.com/mate-desktop/mate-control-center/commit/39028e317750bcc4c81d762c25f2c88f5c8f3f56
https://github.com/mate-desktop/mate-control-center/commit/50e94dbf3140a45cd54b5b6b58e063f9e131dac1

**Comment by zhuyaliang** [comment]
Okay, I'll finish the job.
@raveit65  @yetist 
 Because of an operation error, I forced a PR to be merged.[https://github.com/mate-desktop/mate-control-center/commit/2bccfe30196b7d2c0f11b9e789e10705f97e56a5](url)I'll be careful in the future

**Comment by raveit65** [comment]
@zhuyaliang 
The problem is not that you merged the PRs.
It's more that you created this merge commits.
Example:
```
git: merge without merge commit

etc.

git checkout -b pudh4418-fix-200 master
git pull git://github.com/pudh4418/mate-control-center.git fix-200
git rebase master
git checkout master
git merge --ff-only pudh4418-fix-200
git push
```
Or when using internet browser than use the rebase+ merge button.

**Comment by raveit65** [comment]
And you can't change this because it is very bad to do  a git push on master, because you will break the local git of all other peoples.

**Pull request merged**
