### PR TITLE
Legal

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
```
[rave@satellite mate-control-center]$ git checkout -b rbuj-legal master
Switched to a new branch 'rbuj-legal'
[rave@satellite mate-control-center]$ git pull https://github.com/rbuj/mate-control-center.git legal
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8 (delta 5), reused 8 (delta 5), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/rbuj/mate-control-center
 * branch            legal      -> FETCH_HEAD
Auto-merging help/Makefile.am
CONFLICT (content): Merge conflict in help/Makefile.am
Automatic merge failed; fix conflicts and then commit the result.
```
This is because "Use make functions for HELP_LINGUAS" is already in master.
Can you please rebase this branch against master?
- update your master with upstream master
- run `git rebase master` in this branch to sync this branch with your master.
- run `git push -f` to update your github repo and this PR.

This should fix the problem.

**Comment by raveit65** [comment]
hold on, i could solve the problem local.
I all works fine i will merge it.

**Comment by raveit65** [comment]
Thanks, this works better.

**Comment by rbuj** [comment]
OK

**Pull request merged**
