### PR TITLE
make all three window focus modes selectable (fixes *marco* #140)

### PR DESCRIPTION
**Pull request by frimam**
This clears the issue #140 in marco and the third point on the roadmap for 1.14.  I hope it's correct that I added my name to the list at the top.

### CODE REVIEW

**Comment by monsta** [comment]
Nice, I was going to work on this soon, but looks like this might save me some time :smile:
I'll check this later.

**Comment by monsta** [comment]
Works good with a minor exception: when I try to set the focus mode via dconf-editor and the current mode is "click", I can't change it to "mouse". When I do that, it automatically becomes "sloppy" instead. After that, I can change "sloppy" to "mouse". I guess it's related to the way these nested checkboxes work here...

You can test it with dconf-editor as well (```org.mate.Marco.general -> focus-mode```).

@flexiondotorg @raveit65 do you wish to test this guys?

**Comment by raveit65** [comment]
no, i trust you :)
I can test this with first 1.13 release

**Comment by frimam** [comment]
I added a new commit to fix this behavior. The reason was that the settings are updated after each change of one of the check buttons so that there was the wrong setting saved. Now it works also next to external tools like dconf-editor.

**Comment by monsta** [comment]
Cool, thanks, it works properly now :smile:

**Comment by monsta** [comment]
Squashed into one commit and merged in https://github.com/mate-desktop/mate-control-center/commit/1b111a4e2698705026781b9bbc998bad019cf350.

**Pull request closed without merging**
