### PR TITLE
theme-util.c: fix reinstalling the deleted theme can cause failure

### PR DESCRIPTION
**Pull request by zhangxianwei8**
fixes https://github.com/mate-desktop/mate-control-center/issues/322

Signed-off-by: Zhang Xianwei <zhang.xianwei8@zte.com.cn>
@raveit65

### CODE REVIEW

**Comment by zhangxianwei8** [comment]
@raveit65 @lukefromdc Could you please review the code? Thanks:)

**Comment by raveit65** [comment]
This works now, the theme will complete uninstall from ~/.themes/
I see only one little issue.
If you reinstall the same theme after you removed it and you didn't closed mate-appearance-properties window, the thumbnail won't be recreated.
You need to re-open mate-appearance-properties to see the thumbnail.
If you install another theme the thumbnail for this theme is created fine and the theme is selectable at this point.
But i don't think that this behaviour is related to the PR.

**Comment by sc0w** [comment]
capplets/appearance/theme-installer.c **100644 → 100755** <- that change is needed?

**Comment by zhangxianwei8** [comment]
I don't why the file's attr was changed. :-( Now I have already modified it. Thanks. @sc0w

**Comment by zhangxianwei8** [comment]
@raveit65 Hi, could you please review the code? Thanks:)

**Pull request merged**
