### PR TITLE
UI: avoid deprecated widgets

### PR DESCRIPTION
**Pull request by raveit65**
i hope all looks like before ;-)

### CODE REVIEW

**Comment by monsta** [comment]
```
$ mate-appearance-properties 

(mate-appearance-properties:19289): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(mate-appearance-properties:19289): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(mate-appearance-properties:19289): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(mate-appearance-properties:19289): Gtk-CRITICAL **: gtk_bin_get_child: assertion 'GTK_IS_BIN (bin)' failed
```

**Comment by monsta** [comment]
Mouse properties dialog has some labels centered - looks weird:

mate-mouse-oddities

**Comment by raveit65** [comment]
I didn't saw that as german words are longer ;-)
I will align them to  the left side

**Comment by monsta** [comment]
Use ```LC_ALL=C mate-mouse-properties``` for the default locale :slightly_smiling_face:

**Comment by raveit65** [comment]
This is not the problem.
All those labels use
```
 <property name="halign">start</property>
```
ie for timeout_label
https://github.com/mate-desktop/mate-control-center/blob/master/capplets/mouse/mate-mouse-properties.ui#L669
If i use xalign=0 than they are at the left side.
But than glade complains about a deprecated widget.
Maybe glade is wrong here?
I recall that we use xalign for labels for replacing gtk_misc_alignment.

**Comment by monsta** [comment]
Indeed, we use it in the code, and it's only for GTK+ >= 3.16. The docs say [the same](https://developer.gnome.org/gtk3/stable/GtkLabel.html#GtkLabel--xalign). It's not deprecated for sure...

**Comment by raveit65** [comment]
Ok, i will verify if it works for 3.14 (RHEL) too, otherwise i have a upgrade problem for 1.18 if i use {x/y}align.

**Comment by raveit65** [comment]
@monsta 
https://github.com/mate-desktop/mate-control-center/commit/84046ddf426fac7ac36b56fc488b830a8962f6a8
This works out of box with 3.14 and generate no runtime warnings.

**Comment by monsta** [comment]
Good, but labels near sliders are still centered :slightly_smiling_face:

**Comment by raveit65** [comment]
Which labels?
Please be specific.....

**Comment by raveit65** [comment]
Those warnings are coming from removing deprecated 
```
<object class="GtkHandleBox" id="toolbar_handlebox">
```
Looks like the is an remnant in code itself.

**Comment by raveit65** [comment]
Ok, i need to remove the deprecated GtkHandleBox here too.
https://github.com/mate-desktop/mate-control-center/blob/master/capplets/appearance/appearance-ui.c#L29

**Comment by raveit65** [comment]
@monsta 
Can you please test this UI file before i commit.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Test/appearance.ui
I didn't removed GtkHandleBox here, this needs to be done in code first.
Maybe replacing it with a GtkBox? But this seems to be a bit overdosed.
align --> GtkBox --> Toolbar
better
align --> Toolbar

**Comment by raveit65** [comment]
@monsta 
please test https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Test/mate-mouse-properties.ui
...i don't think it looks better but i don't care ;-)

**Comment by monsta** [comment]
Mouse UI seems ok.

**Comment by monsta** [comment]
Warnings from appearance are gone. I didn't even know we had a handlebox there.

**Comment by monsta** [comment]
Ah, I see. It was added along with the last tab in https://github.com/mate-desktop/mate-control-center/commit/57026bf522ee80d8fc3710ca33da73ff103f98c3. The code should react to ```toolbar-detachable``` key from ```org.mate.interface``` schema and make the sample toolbar detachable from the window... only that it doesn't happen, at least with GTK+ 3.18.9 here.

**Pull request merged**
