### PR TITLE
Fix same size for all icons in Preferred Applications selector

### LINKED ISSUE #358: Default Applications shows icons at different sizes, causing misalignment
#### Actual behaviour

sil-1009810219822665728-dgorbd1xuael8-s

#### Expected behaviour

The dropdown lists should be the same width.

#### Steps to reproduce the behaviour

Open "Preferred Applications".

Whether this problem exhibits is probably dependent on icon themes, but the basic issue is that the icons should be displayed at the same width, regardless. It would be fine I think to display a smaller icon inside an invisible box the width of a larger icon, but the key point is that the dropdown lists not lining up looks ugly.

I think this is fixable in `mate-control-center/master/capplets/default-applications/mate-default-applications-properties.ui` but I'm not sure how best to tell a Gtk Image to always be a certain explicit width and to display the "actual" image centred in that width, or whether there's a better way to solve it.

#### MATE general version

1.20.1.

#### Package version

1.20.2-2ubuntu1

#### Linux Distribution

Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by tamplan**
Hi,

Fixes #358

Regards

### CODE REVIEW

**Comment by tamplan** [comment]
Hi,

Changes done.

Regards,
Laurent

----- Mail original -----
De: "Martin Wimpress" <notifications@github.com>
À: "mate-desktop/mate-control-center" <mate-control-center@noreply.github.com>
Cc: "tamplan" <tamplan@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Samedi 11 Mai 2019 01:14:20
Objet: Re: [mate-desktop/mate-control-center] Fix same size for all icons (#442)



@flexiondotorg requested changes on this pull request. 

Thanks for working on this! 😃 Code looks clean, no new warnings introduced. More importantly, this does fix the icon sizes in Preferred Applications selector. 

I would request one change, please restore {"document_image", "application-pdf"} . Using an icon for a drawing application doesn't make sense. Other than that, this looks good.

**Comment by sc0w** [comment]
little changes in one file, all the commits must to be squashed into one

**Comment by raveit65** [comment]
I squashed your PR to one commit local, the result is:
```
commit 8d3fe3b2da0655101ccedd58c6413f1df939c7ed (HEAD -> tamplan-master)
Author: tamplan <50292710+tamplan@users.noreply.github.com>
Date:   Fri May 10 20:04:06 2019 +0200

    Fix the icon sizes in Preferred Applications selector
    
    Solve this issue https://github.com/mate-desktop/mate-control-center/issues/358

diff --git a/capplets/default-applications/mate-da-capplet.c b/capplets/default-applications/mate-da-capplet.c
index de7c36b..65c53c0 100644
--- a/capplets/default-applications/mate-da-capplet.c
+++ b/capplets/default-applications/mate-da-capplet.c
@@ -334,7 +334,7 @@ static struct {
        {"video_image",        "video-x-generic"},
        {"text_image",         "text-editor"},
        {"terminal_image",     "terminal"},
-       {"document_image",     "application-pdf"},
+       {"document_image",     "x-office-drawing"},
        {"word_image",         "x-office-document"},
        {"spreadsheet_image",  "x-office-spreadsheet"},
        {"calculator_image",   "accessories-calculator"},
```
Is this really what you want?
What i did:
```
git checkout -b tamplan-master master
git pull https://github.com/tamplan/mate-control-center.git master
git rebase master
[rave@mother mate-control-center]$ git log
commit 3a3229dcd6051b244dba2c49ebd6b74398d504dc (HEAD -> tamplan-master)
Author: Laurent Napias <tamplan@free.fr>
Date:   Sat May 11 12:07:38 2019 +0200

    Fix the icon sizes in Preferred Applications selector

commit e6502bb64acaecc3746a2f12e917d88388ae7e36
Author: tamplan <50292710+tamplan@users.noreply.github.com>
Date:   Fri May 10 20:04:06 2019 +0200

    Fix icons size
    
    Solve this issue https://github.com/mate-desktop/mate-control-center/issues/358

commit eafb5fddf84324ebf6b0cc90422f10ee314b5b28 (origin/master, origin/HEAD, master)
Author: rbuj <robert.buj@gmail.com>
Date:   Tue May 7 00:05:26 2019 +0200

    capplets: Use gresources for UI files

git rebase -i eafb5fddf84324ebf6b0cc90422f10ee314b5b28
```
Now i have chosen `squash` in vi editor in terminal.

**Comment by tamplan** [comment]
Hi,
It's exactly that!
Thank you very much, I lack practice in using Gihub :(

**Comment by flexiondotorg** [comment]
@raveit65 That is not what we want. The PR should preserve document_image and application-pdf

**Comment by raveit65** [comment]
>  I lack practice in using Gihub...

For this reason i posted the git commands.
`git rebase -i <last-commit-id-before-your-commit>`
opens a vi-editor in your terminal where you can choose pick/drop/edit/rename/squash commits.
This command is genius, you will love it :)
After all is done you need to do a `git push -f` (force, can't be undo!) to update you github repo.
An existing PR will be updated automatically.

But i am confused that you only want to change this line?
```
-       {"document_image",     "application-pdf"},
+       {"document_image",     "x-office-drawing"},
```

**Comment by tamplan** [comment]
Hi,
I think i have squashed the commits in one.

Regards

**Comment by raveit65** [comment]
Hmm, see what you did in browser.
https://patch-diff.githubusercontent.com/raw/mate-desktop/mate-control-center/pull/442.patch
There are 3 commits.
Subject: [PATCH 1/3] add icon for the font viewer window
Subject: [PATCH 2/3] Fix icons size
Subject: [PATCH 3/3] Fix the icon sizes in Preferred Applications selector

First one is already in master, but ignore them or learn to update you master branch. But this commit isn't the problem.
It seems that [PATCH 3/3] revert [PATCH 2/3]

If i try to squash them local i get this warning.
```
rave@mother mate-control-center]$ git rebase -i eafb5fddf84324ebf6b0cc90422f10ee314b5b28
interactive rebase in progress; onto eafb5fd
Last commands done (2 commands done):
   pick 81bc8af Fix icons size
   squash bb90e6e Fix the icon sizes in Preferred Applications selector
No commands remaining.
You are currently rebasing branch 'tamplan-master' on 'eafb5fd'.

No changes
You asked to amend the most recent commit, but doing so would make
it empty. You can repeat your command with --allow-empty, or you can
remove the commit entirely with "git reset HEAD^".
Could not apply bb90e6e... Fix the icon sizes in Preferred Applications selector
```

**Comment by tamplan** [comment]
What is the solution for me?

**Comment by raveit65** [comment]
Is `Subject: [PATCH 2/3] Fix icons size` the right commit?
If yes, you can remove the third commit with the `git rebase -i <last-commit-id-before-your-commit>`
Or use `git reset HEAD^ --hard` for removing the last commit.
After all do a `git push -f` to update your github remote repo.

**Comment by tamplan** [comment]
Can i delete my repo on Github and repurpose a pull request?
Is this the best solution?
I notice there is "x-office-drawing" in the c ile instead of "application-pdf"...

**Comment by raveit65** [comment]
> Can i delete my repo on Github and repurpose a pull request?

Sure, than you have to open a new PR. Might be easier.
With a new repo i suggest to work on a new branch.
`git checkout -b <new-branch-name`
Than you can easily update your master branch with our master when something is changed.

**Comment by tamplan** [comment]
Ok, in that case, let's go.
Thanks for your help!
Regards.

**Comment by tamplan** [comment]
Please delete this PR, i have made a new one.
Thanks!

Regards

**Comment by raveit65** [comment]
Closing a PR is simple :)

**Pull request closed without merging**
