### PR TITLE
Fixed crash when install/remove application.

### PR DESCRIPTION
**Pull request by yetist**
Fixed issue #403

If m-c-c is open, install/uninstall application, m-c-c is crash.

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
You can create branches for a PR directly here in this repo now.
No need to fork the repo first  :wink:

**Comment by raveit65** [comment]
I can confirm that the PR still fixes the crash, but the repeating warnings remain in terminal if i install/uninstall an application.

```
(mate-control-center:19304): GLib-GObject-WARNING **: 12:09:19.499: invalid unclassed pointer in cast to 'GtkWidget'

(mate-control-center:19304): Gtk-CRITICAL **: 12:09:19.499: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

<cut>
```
Good is that the warnings aren't in in xsession-errors or journal, so we don't spam logs.

**Comment by raveit65** [comment]
Ok, the remaining warnings are still there with fedora 28 and m-c-c-1.20.3.
So the crash is fixed well.

**Comment by yetist** [comment]
The bugs I found in #403 has been fixed now, please review the code and test it, thank you.

Note: The three commits fix different issues, so should keep that, don't squash them.

**Comment by raveit65** [comment]
I tested it again all warnings are gone. Thanks a lot.

**Comment by yetist** [comment]
Yes, there is a memory leak, now it fixed.

**Comment by raveit65** [comment]
Works fine in another test.

**Comment by yetist** [comment]
> @yetist
> Warnings are still there in 1.20 branch. I guess i need to back port only the last 2 commits ?

Yes, I think so.

**Pull request merged**
