### PR TITLE
Remove some compilation warnings

### PR DESCRIPTION
**Pull request by zhuyaliang**
1 Remove compilation warnings for time-admin and mouse
2 Disable manual modification of time after NTP is opened
3 Remove unused files

### CODE REVIEW

**Comment by raveit65** [comment]
> [rsvg_internals/src/svg.rs:84] &self.load_options.base_url = None

@rbuj 
Those warnings is see with several mate applications since some weeks, also without this PR.

**Comment by rbuj** [comment]
@raveit65 It's a librsvg debug issue, it was closed 4 days ago.
https://gitlab.gnome.org/GNOME/librsvg/issues/464

**Comment by zhuyaliang** [comment]
@rbuj We did the same thing.

**Comment by rbuj** [comment]
@zhuyaliang 
Your [new commit](https://github.com/mate-desktop/mate-control-center/pull/465/commits/1b4a14629594f3b45e66a3a7aec8532c4c9eb949) is subsequent to my [previous comment](https://github.com/mate-desktop/mate-control-center/pull/465#issuecomment-502608581) in https://github.com/orgs/mate-desktop/dashboard, and https://github.com/mate-desktop/mate-control-center/pull/466 is prior. I think that I sent it before.

**Comment by raveit65** [comment]
Mail notification from this PR is from Sun, 16 Jun 2019 23:32:29 -0700.
Notification from other PR is from Mon, 17 Jun 2019 02:07:08 -0700.
Same with mouse-tooltip here in browser.

**Comment by rbuj** [comment]
https://github.com/mate-desktop/mate-control-center/commit/b1451cfc8a0c814922f0721c62d2a178c56a18d3 sent by @zhuyaliang didn't remove capplet-stock-icons.h/c files among other changes.

**Comment by zhuyaliang** [comment]
This PR contains some changes to ```time-admin```. If you can include these changes to ```time-admin``` in your submission, I can cancel the merge request.

**Comment by rbuj** [comment]
I won't include the changes that you performed in time-admin on https://github.com/mate-desktop/mate-control-center/pull/466, since you are the author of those changes.

**Comment by zhuyaliang** [comment]
So how to deal with this PR

**Comment by rbuj** [comment]
Overwrite non related files with your PR using the files pulled from parent commit. Next, send only the related files to each commit subject. What's more, one PR by subject. For instance:

### time-admin: Fix memory leaks
- capplets/time-admin/src/time-zone.c
- capplets/time-admin/src/time-zone.h

Missing g_error_free(error); https://github.com/mate-desktop/mate-control-center/pull/456#pullrequestreview-247530903

### time-admin: Enable/disable form controls using ntp-state and user-permission
- capplets/time-admin/src/main.c

**Comment by raveit65** [comment]
Would be nice if you guys find an agreement, we can't merge both PRs.

**Comment by zhuyaliang** [comment]
@raveit65 
Okay, I should be the first to modify ```mouse```, but for other reasons I submit later than other developers, I will revoke this PR， Individual submission of changes to```time-admin```

**Comment by raveit65** [comment]
@rbuj 
In my mailbox this PR was first arrived. Would be nice if you can check notification in your mailbox to avoid double work next time.
Thanks.

**Comment by rbuj** [comment]
@raveit65 I can't understand you when you say that I have to read my mbox. From travis PR log:

1. I reviewed this PR (https://github.com/mate-desktop/mate-control-center/commit/b1451cfc8a0c814922f0721c62d2a178c56a18d3)
2. I sent a [comment](https://github.com/mate-desktop/mate-control-center/pull/465#pullrequestreview-250327898) to the author.
3. I started my [new PR](https://github.com/mate-desktop/mate-control-center/pull/466).
4. I sent you a [comment](https://github.com/mate-desktop/mate-control-center/pull/465#issuecomment-502608581).
5. About 30 minutes later (3), the author of this pull request send a forced update (https://github.com/mate-desktop/mate-control-center/commit/1dffa61) adding my contributions which I sent in another PR.
6. Next, the author of this pull request said that [we did the same](https://github.com/mate-desktop/mate-control-center/pull/465#issuecomment-502611596).
7. Finally, you said that I have to check my mbox to avoid duplicate effort.

**Comment by raveit65** [comment]
Again, from my mail log. I received this pr 3 hours before you opens yours.
```
Mail notification from this PR is from Sun, 16 Jun 2019 23:32:29 -0700.
Notification from other PR is from Mon, 17 Jun 2019 02:07:08 -0700.
```

So i am 100% sure that this PR was the first one.

**Comment by rbuj** [comment]
@raveit65 

Did both authors fix the same build error fixing po/POTFILES.in?
- diff between https://github.com/mate-desktop/mate-control-center/commit/1e5bc7c  and https://github.com/mate-desktop/mate-control-center/commit/e3129ea
- diff between https://github.com/mate-desktop/mate-control-center/commit/1dffa61  and https://github.com/mate-desktop/mate-control-center/commit/9176a81

Did you see the screenshot attached in https://github.com/mate-desktop/mate-control-center/pull/465#issuecomment-502633791 (top is newer, bottom is older)?

**Pull request closed without merging**
