### PR TITLE
Desktop icons Mate Control Center

### PR DESCRIPTION
**Pull request by tamplan**
This m-c-c applet permits you to show or hide and rename icons on the desktop:
- allows you to choose which icon to display
- allows you to rename some icons

Launching the applet.
First GTKChekButton allows you to show or not all the icons then one GTKChekButton by icon to do the same:
Capture du 2019-06-12 21-44-09
Select 'Modifer' button ('Edit' in my native language) allows you to rename the icon (hiding GTKChekButton and showing GTKEntry):
Capture du 2019-06-12 21-45-31
Select 'Annuler' button ('Cancel' in my native language) reset the name to his default value.

If PR is approved, can someone can help me to proceed to add new entries in mate-control-center.pot and write man and help pages?

Thanks you very much in advance.
Regards

### CODE REVIEW

**Comment by tamplan** [comment]
configure.ac should be updated to compile application, right?

**Comment by tamplan** [comment]
Hi,

Is there an update i need to do here?

Regards

**Comment by raveit65** [comment]
This can't be merged because of conflicting files.

Conflicting files
capplets/Makefile.am
configure.ac

**Comment by tamplan** [comment]
Hi,
I have seen that but i have this message on that page:
Capture du 2019-06-16 09-04-50
I don't understand how to resolve this (i don't have write access) and no information where the conflict is (a commit done by someone else under theses files?)

Thank for any help on this...

Regards

**Comment by raveit65** [comment]
Ok, main problem is that your master branch isn't in sync with our master.
You need to fix this in a terminal. Let start.
1 . Adding upstream master to your repo.
git checkout master
git remote add upstream git@github.com:mate-desktop/mate-control-center.git  (if you use a ssh key)
git remote add upstream https://github.com/mate-desktop/mate-control-center.git  (if you use https)

git pull upstream master      (this pulls in latest changes from our master branch)

git push origin           (pushing changed to your master branch at  your github repo

2. syncing your desktop-icons branch with your updated master.
git checkout desktop-icons

git rebase master 

If you get conflicts at this point you need to solve them here.
If everything is fine than push your fixed branch to github with

git push -f  (--force)

PR should be updated automatic.

I hope this helps you......

**Comment by tamplan** [comment]
Yes, thanks for your help!

**Comment by tamplan** [comment]
I prefer to wait more before to purpose this PR, capplets/Makefile.am is updated by https://github.com/mate-desktop/mate-control-center/pull/462 awaiting validation.

**Pull request closed without merging**
