### PR TITLE
Adding search option for mate-font-viewer

### PR DESCRIPTION
**Pull request by selectiveduplicate**
Referencing issue #359 in this regard.
I'm dubious about the "search bar" though, it could've been implemented better, but this is what I've been able to...
So any advice/criticism would be appreciated...

### CODE REVIEW

**Comment by selectiveduplicate** [comment]
@lukefromdc The latest commit should fix the "incompatible pointer" issue... can you kindly check? 
I was a little busy for my exam so couldn't make time to sit for investigating this sooner...

**Comment by raveit65** [comment]
typing something in search field produces warnings.
```
(mate-font-viewer:24061): Gtk-CRITICAL **: 15:48:16.539: gtk_tree_model_filter_real_unref_node: assertion 'elt->ref_count > 0' failed
```
but gnome-font-viewer generates the same warning and xfce stated this as a gtk+ issue.
https://wiki.xfce.org/releng/4.14/roadmap/xfce4-appfinder
https://gitlab.gnome.org/GNOME/gtk/issues/1150
Not sure if this is an gtk+ issue in our case and we can ignore it.
Thoughts?

Besides from that it looks good.

**Comment by selectiveduplicate** [comment]
I have noticed it issue too, but have no clue what to do about it; I'm pretty much a noob in GTK+! :disappointed_relieved: 

Looking at the code [here](https://gitlab.gnome.org/GNOME/gtk/blob/master/gtk/gtktreemodelfilter.c#L1091), [here](https://gitlab.gnome.org/GNOME/gtk/blob/master/gtk/gtktreemodelfilter.c#L1091), [here](https://gitlab.gnome.org/GNOME/gtk/blob/master/gtk/gtktreemodelfilter.c#L1708), and [here](https://gitlab.gnome.org/GNOME/gtk/blob/master/gtk/gtktreemodelfilter.c#L2609), the issue is getting triggered when using ``GTK_TREE_MODEL_FILTER`` macro in this PR commit (line 547). The assertion ``elt->ref_count > 0`` is in each of these four parts...

Most probably has something to do with the "reference counts" of nodes...

**Comment by raveit65** [comment]
Ok, i will squash all to 1 commit and merge it.

**Comment by raveit65** [comment]
rebased and merged https://github.com/mate-desktop/mate-control-center/commit/b245b8d8530da70e6d5b31c52df89dd8055ec6b6
Thanks

**Comment by selectiveduplicate** [comment]
Fixes #359

**Pull request closed without merging**
