### PR TITLE
add archlinux build on travis-ci

### PR DESCRIPTION
**Pull request by yetist**
Add archlinux build, change some before_scripts, delte the last line after make distcheck.

When after merge #415 , this PR will be ok to use.

### CODE REVIEW

**Comment by raveit65** [comment]
Hmm, weird, travis failed for debian again during distcheck, but only for PR check.
Push check is fine.
Sadly, not all lines of output are displayed.
Something with translations in /po folder is wrong.
Someone with debian installed around?

**Comment by yetist** [comment]
Can you show me the log?
BTW, If add more -v/--verbose will see the full output.

**Comment by raveit65** [comment]
Log is at travis build https://travis-ci.org/mate-desktop/mate-control-center/jobs/490087145

**Comment by yetist** [comment]
After rebase on master, this will be ok, let's see the build log.

**Comment by raveit65** [comment]
Damned , i forgot that. :)

**Pull request merged**
