### PR TITLE
libslab-utils: Remove dead function libslab_get_current_screen

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
Oh no, we have a merge conflict :)

**Comment by rbuj** [comment]
@raveit65 done

**Review by vkareh — APPROVED** [review]
LGTM

This function is not used anywhere in this (or any other mate-desktop) repo

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, same runtime behavior as before. If anything used this, the build would fail. Good to go

**Pull request merged**
