### PR TITLE
port GdkColor to GdkRGBA

### PR DESCRIPTION
**Pull request by raveit65**
Note, those PRs belongs to this one.
mate-desktop/mate-desktop#230
https://github.com/mate-desktop/caja/pull/577

### CODE REVIEW

**Comment by lukefromdc** [comment]
I just found the basis for a possible workaround for the black preview for a solid color BG: It turns out if you set a "gradient" of two colors that are the same color the preview now works. If nothing else works, the solid color BG could be special cased as a gradient of the start color with the start color for the preview button.

**Comment by raveit65** [comment]
For testing i disabled 'appearance-desktop: port GdkColor to GdkRGBA' commit, and the hex color values are back in gsettings keys.
But thumbnail preview is black with solid color.
So it doesn't make any different if those values are hex or rgb for the thumbnail creation.

> If nothing else works, the solid color BG could be special cased as a gradient of the start color with the start color for the preview button.

yeah, that might be a solution.
For the moment i like to find out how the creation of the thumbnails  exactly works in code.

**Comment by lukefromdc** [comment]
appearance-desktop.c has an include for mate-desktop-thumbnail.h
which is in mate-desktop/libmate-desktop. I will now look there for
any new answers

**Comment by raveit65** [comment]
there are some functions in mate.bg.c where a thumbnail is created, but after reading the code whole the day today, my hat steamed and i don't know more.

**Comment by raveit65** [comment]
@lukefromdc 
I talked with monsta at irc and we want to merge the 3 GdkRGBA PRs like they are for the moment, if you agree.
Because we think  the regression on preview with solid colors is very minor.
1. Using a solid color works on desktop
2. Our default is using gradiant colors, so only a few uses will see that.
3. Of course i will open a report as reminder to fix it.
4. after merging we can start to work on your PR and others.

**Comment by lukefromdc** [comment]
I am for that, it will make my work far easier if this is merged to master
as it stands now as I will be able to work on other deprecations and this
GTK 3.21.3 stuff wiithout worrying about generating merge conflicts.

Let's get this done.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-control-center/commit/40d833ec5846a7e2f4bbe7bf794e6f5bebe15d00
https://github.com/mate-desktop/mate-control-center/commit/c771b2c0a4cf30b55dfe0d7c6b38abc6bfc854d2
https://github.com/mate-desktop/mate-control-center/commit/42d3d76f542ef4d401284d4b616ed8b4f55b9bed
https://github.com/mate-desktop/mate-control-center/commit/7c6ca27018bfd41a82c0732e9a371c3e6112b55d
https://github.com/mate-desktop/mate-control-center/commit/cd3114cbfab295c38fe629a3f6688645b3f60015

**Comment by raveit65** [comment]
> wiithout worrying about generating merge conflicts.

@lukefromdc 
to avoid that after another PR is merged.
1. sync you fork with upstream
git remote add upstream git://github.com/user/repo.git
git pull upstream master
git push origin (this pushed new upstream commits from your local repo to you github repo)
2. switch to you local branch where you did the PR and sync the branch with your updated master
git checkout blablabla
git rebase master
3. if rebase works fine than do a
git push -f
for updating the branch at github.
The PR will be updated automatic at this point.

**Comment by lukefromdc** [comment]
I just rebased my PR to replace deprecated gdk_cairo_create with
cairo_create on today's master, another manual job as I so far I've
only figured out now to work with master (not branches) from the 
command line. New PR ready to go is at:

https://github.com/mate-desktop/caja/pull/582

I've been running this code for almost two weeks with no ill effects 
observed in various GTK 3.21 versions.

**Comment by lukefromdc** [comment]
Just closed https://github.com/mate-desktop/caja/pull/582, it turns out gdk_cairo_create is only used in GTK2 already and the build code was not changed one bit-and had it been used it would not have worked. Thus, https://github.com/mate-desktop/caja/pull/578 should be next in line for Caja, I tested it a few days ago and it works.

**Pull request closed without merging**
