### PR TITLE
Add support for checking .ui accessibility with gla11y

### PR DESCRIPTION
**Pull request by sthibaul**
As provided from https://github.com/hypra/gla11y

### CODE REVIEW

**Comment by sthibaul** [comment]
Hello,

This is a first iteration for adding .ui file accessibility checkup with the gla11y tool. The idea would be to have gla11y installed on the CI infrastructure so that no accessibility regression is introduced, that would be caught by gla11y. As gla11y says, the warnings and their resolution is described on https://github.com/sthibaul/gla11y/blob/master/README.md

Eventually, the existing warnings (suppressed by this commit) should be fixed and the corresponding suppression rules removed.

Samuel

**Comment by alexarnaud** [comment]
@raveit65 Following our recent discussion about maintaining a11y into Mate, this PR is intended to help us to make this possible.

Best regards,
Alex.

**Comment by sthibaul** [comment]
Any news on this?

**Comment by raveit65** [comment]
Honestly, we need someone in the team who can handle all this accessibility technologies.

**Comment by lukefromdc** [comment]
I don't have that tool installed and know little of it. Accerciser at least I have a little familarity with though not a lot it has been enough to get past Orca not generating sound (ever) due to speech-dispatcher issues on my system.

**Comment by sthibaul** [comment]
Fixing gla11y warnings should be easy enough. As the tool advertises when warnings are produced, a howto is provided in the gla11y repository: https://github.com/hypra/gla11y/blob/master/HOWTO.md

**Comment by raveit65** [comment]
> Fixing gla11y warnings should be easy enough

yes, but we need manpower to do this.....

Any way , i will merge it. Looks like no other reviewer can confirm a11y changes.
Let see what happens :)

**Comment by alexarnaud** [comment]
Le 15/06/2019 à 17:21, raveit65 a écrit :
>     Fixing gla11y warnings should be easy enough
> 
> yes, but we need manpower to do this.....

Right, we only want to prevent new regression, don't worry if you don't 
have the time to do more. You really do a great job :).

Thanks a lot for merging this!

**Comment by raveit65** [comment]
> Right, we only want to prevent new regression, don't worry if you don't have the time to do more. You really do a great job :). Thanks a lot for merging this!

Thanks for thanks, this is friendly but doesn't solve any problem ;)
I would really like to see that someone of your guys enter core-team to handle coding and reported issues of accessibility support.

**Comment by sthibaul** [comment]
Thanks for merging this!

So, can we now consider adding support in the MATE CI, to really enforce not getting regressions?

I have prepared a Debian package for gla11y, available on https://people.debian.org/~sthibault/tmp/sid-tmp/gla11y_0.1-1_amd64.deb , which I'll upload to Debian unstable (but it might take months to get past the copyright review there).

Can we perhaps modify the CI script to install this package so that configure find the gla11y tool and use it to check the .ui files? That way we'll catch any future accessibility regression.

**Comment by alexarnaud** [comment]
@raveit65 We really would like to have one of us to be part of the core team. If @cwendling is OK and you are OK for this he will be the Hypra's person into the Mate core team.

Best regards,
Alex.

**Comment by cwendling** [comment]
@raveit65 I'd be happy to join and help with this.  Maybe you'd have to ping me/point to me accesibility issues I need to work on because I unfortunately am fairly busy so sometimes bug reports fall through my quick triaging process, but I'd be happy to try and deal with them anyway (once they have been identified, they usually are my concern anyway :slightly_smiling_face:).

**Comment by raveit65** [comment]
@cwendling 
Thanks :)
Of course i can ping you on accessibility issue when i read them. 
When i add you to core-team you will get email notification from every Issue or PR.
So, you should get informed about an accessibility issue.
I hope you don't disable notifications from github after i added you to team ;)
Personal i am using different email addresses/boxes in my email client, to avoid to spam my private email traffic with linux mails from MATE and Fedora.
Maybe you like to change your email address for github before i add you to the team?

Of course i need to ask the other guys.
@mate-desktop/core-team 
Do you agree with adding Colomban Wendling to core-team?

**Comment by cwendling** [comment]
@raveit65 nah it's OK I already have appropriate filters set up in my email client so it's sorted out nicely, but there's quite a little bit of traffic on all the MATE projects (I should be subscribed to them all if I didn't miss anything), so it's not unthinkable I would miss something going through the news in the morning :)

**Comment by rbuj** [comment]
I agree in adding @cwendling to core-team.

**Comment by flexiondotorg** [comment]
I agree that @cwendling should join the core-team. Perhaps we can create a GitHub Project and add all current and new a11y issues to it?

**Comment by raveit65** [comment]
good idea!

**Comment by alexarnaud** [comment]
I don't think created a dedicated project for accessibility is a good idea. I'd prefer a label.

Having dedicated project for accessibility means less people will look into it and could work on it from the Hypra more than 4 years experience.
Some keyboard issue considered useful for accessibility are also useful for keyboard users without disabilities.
Improving contrast could also benefit for elderly or could improve the user experience.
Keep a11y in mainstreams give it more visibility and demonstrate accessibility is not only for disabled people but could benefit to all.

Some innovation like vibrator mode on phone and remote control have been created for disabled people ans are now used by everybody.

Best regards,
Alex.

**Comment by cwendling** [comment]
@alexarnaud IIUC what @flexiondotorg suggested is to mark the a11y-related issue as belonging to a "project", which is some kind of "power label" if you will.  It doesn't move the issues, it just marks them, and offers overview & more, but they are still standard issues on the relevant repository.

**Comment by alexarnaud** [comment]
@cwendling Oh, thanks for the clarification. In this case, indeed, it's a really good idea.

Best regards,
Alex.

**Comment by raveit65** [comment]
This is our project page (i hope it is public) https://github.com/orgs/mate-desktop/projects ,
and in this issue you can see the label of the project `HiDPI Support`

**Comment by alexarnaud** [comment]
Le 18/06/2019 à 15:11, raveit65 a écrit :
> This is our project page (i hope it is public) 
> https://github.com/orgs/mate-desktop/projects ,
> and in this issue you can see the label of the project |HiDPI Support|

I can open the page but I see "MATE Desktop doesn’t have any public 
projects."
Probably you can verify in opening this page with your browser in 
private mode.

Best regards,
Alex.

**Comment by raveit65** [comment]
Maybe i should add you to Contributors group for making it visible for you?

**Comment by sthibaul** [comment]
Could we also discuss adding the gla11y to at least one of the CI images, for instance the Debian one with the package I uploaded?

**Comment by raveit65** [comment]
@cwendling 
welcome to the team.

**Comment by raveit65** [comment]
@sthibaul 

> Could we also discuss adding the gla11y to at least one of the CI images, for instance the Debian one with the package I uploaded?

I don't understand what you want....
You mean to add a build dependency to debian dependency at travis config?
https://github.com/mate-desktop/mate-control-center/blob/master/.travis.yml#L85
And what result do you expect?

And please write more than 2 words.
Me and most other people here don't know anything about `a11y`
eg. what is `gla11y`?

**Comment by alexarnaud** [comment]
Le 18/06/2019 à 15:44, raveit65 a écrit :
> Maybe i should add you to Contributors group for making it visible for you?

I agree with you.

Best regards,
Alex.

**Comment by rbuj** [comment]
Gla11y (Glade accessibility) is a Python script which takes .ui files (Glade graphical interface description files), and reports the accessibility issues which can be found with static analysis. From [LOO article](https://blog.documentfoundation.org/blog/2018/05/07/welcome-gla11y-the-user-interface-accessibility-checker/).

**Comment by sthibaul** [comment]
> I don't understand what you want....
> You mean to add a build dependency to debian dependency at travis config?
> https://github.com/mate-desktop/mate-control-center/blob/master/.travis.yml#L85

Yes.

> And what result do you expect?

That the .ui checks will actually be made during CI builds. Currently it is not checking anything, it just runs /bin/true since gla11y is not available in the image.

> Me and most other people here don't know anything about `a11y`
> eg. what is `gla11y`?

Sorry, gla11y was described at the very beginning of this pull request, that's why I thought people discussing here already knew what we were talking about. See https://github.com/hypra/gla11y :

“This tool checks accessibility of GtkBuilder .ui files produced e.g. by glade It looks for various issues, and notably missing or bogus labelling relations.

It can for instance be used in Continous Integration checks to make sure not to introduce accessibility regressions.”

But for CI to actually call gla11y, that tool needs to be installed in the image for the make rules to be able to call it.

**Comment by sthibaul** [comment]
> > I don't understand what you want....
> > You mean to add a build dependency to debian dependency at travis config?
> > https://github.com/mate-desktop/mate-control-center/blob/master/.travis.yml#L85
> 
> Yes.

(but gla11y is not finished uploading in Debian yet, that's why I mentioned taking it from my people.debian.org repository)

**Comment by cwendling** [comment]
@raveit65 The point of the PR here (#440) was to add a means of checking that UI files are accessible.  This means among other things that widgets are properly described with some text, etc.

Such a check is only useful if it is run. This relies on the presence of the [*gla11y*](https://github.com/hypra/gla11y) tool; if not found the tests are just skipped.  So we need to have this tool in order to actually check anything here.

**Comment by yetist** [comment]
@cwendling 
Welcome to the team. Which command should to run on travis for checking that?

**Comment by rbuj** [comment]
@cwendling
Welcome to the team!

**Comment by raveit65** [comment]
@alexarnaud 
Invitation was sent.
Let me know if you can see the projects at project page now.

**Comment by raveit65** [comment]
> The point of the PR here (#440) was to add a means of checking that UI files are accessible.  This means among other things that widgets are properly described with some text, etc.

> Such a check is only useful if it is run. This relies on the presence of the [*gla11y*](https://github.com/hypra/gla11y) tool; if not found the tests are just skipped.  So we need to have this tool in order to actually check anything here.

Got it, thanks for details.

**Comment by cwendling** [comment]
@yetist @rbuj thanks!

@yetist you need to have *gla11y* executable in the system, and then normal build should perform the checks.

**Comment by sthibaul** [comment]
It can be seen easily in the configure log: currently we have

    checking for gla11y... true

`true` being the fallback, and we should instead have

    checking for gla11y... /usr/bin/gla11y

as should be provided by the CI image.

**Comment by alexarnaud** [comment]
Le 19/06/2019 à 11:51, raveit65 a écrit :
> @alexarnaud <https://github.com/alexarnaud>
> Invitation was sent.
> Let me know if you can see the projects at project page now.

I now see them, thanks.

Best regards,
Alex.

**Comment by yetist** [comment]
> @yetist you need to have _gla11y_ executable in the system, and then normal build should perform the checks.

I created #472 for that, let's see if it works

**Pull request merged**
